export const active: string;
export const component: string;
export const icon: string;
export const networkInfo: string;
export const networkInfoIcon: string;
export const paperWalletCreateCertificateIcon: string;
export const redeemItnRewardsIcon: string;
export const stakingDelegationCountdownIcon: string;
export const stakingIcon: string;
