// Ariadne v1 vocabulary, rechecked against official Daedalus
// 6c57eb94753211f66d3a63f49d031bf746044755. Changes require coordinated review.
// Wire categories use the enum keys, not the Matomo display strings.
export const analyticsNetworks = [
  'mainnet',
  'mainnet_flight',
  'preprod',
  'preview',
  'testnet',
  'staging',
  'shelley_qa',
  'alonzo_purple',
  'selfnode',
  'development',
  'vasil_dev',
] as const;

export const analyticsPages = [
  'Data Layer Migration Page',
  'Add Wallet',
  'Wallet Summary',
  'Send Screen',
  'Receive Screen',
  'Tokens',
  'Transactions',
  'Wallet Settings',
  'Wallet UTxO distribution',
  'General Settings',
  'Wallets Settings',
  'Stake Pools Settings',
  'Terms of Use',
  'Support',
  'Display Settings',
  'Security Settings',
  'Staking Countdown',
  'Delegation Center',
  'Stake Pools List',
  'Staking Rewards',
  'Staking Epochs',
  'Staking info',
  'Redeem ITN rewards',
  'Voting Registration',
  'Governance Wallets',
  'Voting Power Delegation',
  'DRep Directory',
  'DRep Favorites',
  'DRep Detail',
] as const;

export const analyticsActions = {
  WALLETS: [
    'Revealed wallet public key',
    'Revealed wallet multi-signature public key',
    'Restored a software wallet',
    'Created a new hardware wallet',
    'Created a new software wallet',
    'Wallet deleted',
    'Transaction made',
    'Saved wallet address as PDF',
    'Saved wallet address as QR code',
    'Changed wallet settings',
    'Verified recovery phrase',
    'Restored legacy wallet(s)',
    'Opened share wallet address modal',
    'Opened native token settings',
    'Set transaction filters',
    'Exported transactions as CSV',
    'Verified wallet address with hardware wallet',
    'Changed native token settings',
    'Added token to favorites',
    'Removed token from favorites',
    'Clicked Show More Transactions button',
    'Removed token from transaction',
    'Added token to transaction',
  ],
  STAKE_POOLS: [
    'Opened delegate wallet dialog',
    'Used stake pools amount slider',
    'Redelegated a wallet',
    'Delegated a wallet',
    'Exported rewards as CSV',
    'Used stake pools search',
    'Changed view to grid view',
    'Changed view to grid rewards view',
    'Changed view to list view',
  ],
  SETTINGS: [
    'Changed SMASH server',
    'Changed user settings',
    'Changed theme',
    'Changed currency',
    'RTS flags disabled',
    'RTS flags enabled',
    'Turned on discreet mode',
    'Turned off discreet mode',
    'Turned on discreet mode by default',
    'Turned off discreet mode by default',
    'Turned on displaying ada balances in other currency',
    'Turned off displaying ada balances in other currency',
  ],
  LAYOUT: [
    'Changed wallet sorting settings',
    'Toggled submenu',
    'Used wallet search',
    'Opened newsfeed',
  ],
  SYSTEM_MENU: [
    'Showed about dialog',
    'Showed diagnostics dialog',
    'Showed toggle RTS flags dialog',
    'Showed ITN rewards redemption dialog',
    'Downloaded logs',
  ],
  VOTING: ['Casted governance vote', 'Registered for voting'],
} as const;

// Only wallet-kind labels have a reviewed semantic meaning in v1. Dynamic
// SMASH URLs, preference values and voting choices must be omitted by a client.
export const walletLabelActions: readonly string[] = [
  'Transaction made',
  'Wallet deleted',
  'Saved wallet address as PDF',
  'Saved wallet address as QR code',
];
export const analyticsCpus = [
  'Other',
  'Other Intel',
  'Other AMD',
  'Intel Core i3',
  'Intel Core i5',
  'Intel Core i7',
  'Intel Core i9',
  'Intel Celeron',
  'Intel Pentium',
  'Intel Xeon',
  'Intel Atom',
  'AMD Ryzen 3',
  'AMD Ryzen 5',
  'AMD Ryzen 7',
  'AMD Ryzen 9',
  'AMD Athlon',
  'AMD FX',
  'AMD EPYC',
  'AMD A4',
  'AMD A6',
  'AMD A8',
  'AMD A10',
  'AMD A12',
  'Apple M1',
  'Apple M1 Pro',
  'Apple M1 Max',
  'Apple M1 Ultra',
  'Apple M2',
  'Apple M2 Pro',
  'Apple M2 Max',
  'Apple M2 Ultra',
  'Apple M3',
  'Apple M3 Pro',
  'Apple M3 Max',
  'Apple M3 Ultra',
  'Apple M4',
  'Apple M4 Pro',
  'Apple M4 Max',
  'Apple M4 Ultra',
] as const;
