// @flow
import {
  COMPRESS_LOGS_CHANNEL,
  DOWNLOAD_LOGS_CHANNEL,
  GET_GPU_STATUS_CHANNEL,
  GET_LOGS_CHANNEL,
  PARSE_REDEMPTION_CODE_CHANNEL
} from './ipc/api';

export const PARSE_REDEMPTION_CODE = {
  REQUEST: PARSE_REDEMPTION_CODE_CHANNEL,
  SUCCESS: `${PARSE_REDEMPTION_CODE_CHANNEL}-success`,
  ERROR: `${PARSE_REDEMPTION_CODE_CHANNEL}-error`,
  INVALID_CERTIFICATE_ERROR: 'invalid certificate',
};

export const GET_LOGS = {
  REQUEST: GET_LOGS_CHANNEL,
  SUCCESS: `${GET_LOGS_CHANNEL}-success`,
};

export const COMPRESS_LOGS = {
  REQUEST: COMPRESS_LOGS_CHANNEL,
  SUCCESS: `${COMPRESS_LOGS_CHANNEL}-success`,
  ERROR: `${COMPRESS_LOGS_CHANNEL}-error`,
};

export const DOWNLOAD_LOGS = {
  REQUEST: DOWNLOAD_LOGS_CHANNEL,
  SUCCESS: `${DOWNLOAD_LOGS_CHANNEL}-success`,
  ERROR: `${DOWNLOAD_LOGS_CHANNEL}-error`,
};

export const GET_GPU_STATUS = {
  REQUEST: GET_GPU_STATUS_CHANNEL,
  SUCCESS: `${GET_GPU_STATUS_CHANNEL}-success`,
  ERROR: `${GET_GPU_STATUS_CHANNEL}-error`,
};
