[build]
command = "yarn && yarn storybook:build"

[build.environment]
YARN_VERSION = "1.22.19"
NODE_VERSION = "18.12.1"
CPPFLAGS = "-I/home/linuxbrew/.linuxbrew/opt/systemd/include -I/home/linuxbrew/.linuxbrew/include"
CXXFLAGS = "-I/home/linuxbrew/.linuxbrew/opt/systemd/include -I/home/linuxbrew/.linuxbrew/include"
LDFLAGS  = "-L/home/linuxbrew/.linuxbrew/opt/systemd/lib -L/home/linuxbrew/.linuxbrew/lib"
PKG_CONFIG_PATH = "/home/linuxbrew/.linuxbrew/opt/systemd/lib/pkgconfig:/home/linuxbrew/.linuxbrew/lib/pkgconfig"
