import { BrowserWindow } from 'electron';
import compressLogsApi from './compress-logs';
import downloadLogsApi from './download-logs';
import { handleElectronStoreChannel } from './electronStoreConversation';
import getLogsApi from './get-logs';
import loadAsset from './load-asset';
import getGpuStatus from './get-gpu-status';
import { downloadManagerChannel } from './downloadManagerChannel';
import getRecoveryWalletIdChannel from './getRecoveryWalletIdChannel';
import { handleHardwareWalletRequests } from './getHardwareWalletChannel';
import { handleBugReportRequests } from './bugReportRequestChannel';
import { handleFileMetaRequests } from './generateFileMetaChannel';
import { handlePaperWalletRequests } from './generatePaperWalletChannel';
import { handleAddressPDFRequests } from './generateAddressPDFChannel';
import { handleVotingPDFRequests } from './generateVotingPDFChannel';
import { saveQRCodeImageRequests } from './saveQRCodeImageChannel';
import { handleRewardsCsvRequests } from './generateCsvChannel';
import { handleFileDialogRequests } from './show-file-dialog-channels';
import { handleAddressIntrospectionRequests } from './introspect-address';
import { handleManageAppUpdateRequests } from './manageAppUpdateChannel';
import { MainIpcChannel } from './lib/MainIpcChannel';
import { createChannels } from './createHardwareWalletIPCChannels';
import { handleMithrilBootstrapRequests } from './mithrilBootstrapChannel';
import { handleMithrilPartialSyncRequests } from './mithrilPartialSyncChannel';
import { handleChainStorageRequests } from './chainStorageChannel';
import { handleWindowControlRequests } from './windowControlChannels';
import { currentWindowSender } from './lib/currentWindowSender';

const hardwareWalletChannels = createChannels(MainIpcChannel);

export default (window: BrowserWindow) => {
  currentWindowSender.bind(window);
  compressLogsApi();
  downloadLogsApi();
  getLogsApi();
  handleWindowControlRequests(window);
  loadAsset();
  getGpuStatus();
  handleBugReportRequests();
  handleFileMetaRequests();
  handlePaperWalletRequests();
  handleAddressPDFRequests();
  handleVotingPDFRequests();
  saveQRCodeImageRequests();
  handleRewardsCsvRequests();
  handleFileDialogRequests(window);
  handleAddressIntrospectionRequests();
  handleManageAppUpdateRequests(window);
  handleMithrilBootstrapRequests(window);
  handleMithrilPartialSyncRequests(window);
  handleChainStorageRequests();
  downloadManagerChannel(window);
  getRecoveryWalletIdChannel();
  handleElectronStoreChannel();
  handleHardwareWalletRequests(window, hardwareWalletChannels);
};
