#!/bin/sh
#
# this script merges the png files into a single ico for windows

for x in mainnet mainnet_flight staging testnet qa nightly itn_rewards_v1 itn_selfnode selfnode; do
  pushd $x
  convert 16x16.png 24x24.png 32x32.png 48x48.png 64x64.png 128x128.png 256x256.png $x.ico
  popd
done
