//  ==== DARK BLUE THEME === //

export default {
  '--preferred-font': '"Times New Roman", serif',

  '--font-ultralight': 'SFUIDisplay-Ultralight',
  '--font-thin': 'SFUIDisplay-Thin',
  '--font-light': 'SFUIDisplay-Light',
  '--font-regular': 'SFUIDisplay-Regular',
  '--font-medium': 'SFUIDisplay-Medium',
  '--font-semibold': 'SFUIDisplay-Semibold',
  '--font-bold': 'SFUIDisplay-Bold',
  '--font-heavy': 'SFUIDisplay-Heavy',
  '--font-black': 'SFUIDisplay-Black',

  '--theme-input-hint-font': 'SFUIDisplay-Regular',

  '--theme-ada-redemption-headline-color': '#e9f4fe',
  '--theme-ada-redemption-instructions-color': '#e9f4fe',
  '--theme-ada-redemption-success-overlay-background-color': 'rgba(38, 51, 69, 0.88)',
  '--theme-ada-redemption-success-overlay-border-color': '#fafbfc',
  '--theme-ada-redemption-success-overlay-message-color': '#e9f4fe',
  '--theme-ada-redemption-success-overlay-button-text-color': '#e9f4fe',
  '--theme-ada-redemption-success-overlay-button-text-color-hover': '#263345',
  '--theme-ada-redemption-success-overlay-button-background-color-hover': '#e9f4fe',
  '--theme-ada-redemption-disclaimer-background-color': 'rgba(171, 23, 0, 0.94)',
  '--theme-ada-redemption-disclaimer-text-color': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-background-color': '#ab1700',
  '--theme-ada-redemption-disclaimer-button-text-color': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-background-color-hover': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-text-color-hover': '#ab1700',
  '--theme-ada-redemption-disclaimer-checkbox-color-check': '#fafbfc',
  '--theme-ada-redemption-disclaimer-checkbox-color-checked': '#fafbfc',
  '--theme-ada-redemption-disclaimer-checkbox-color-after': '#ab1700',
  '--theme-ada-redemption-disclaimer-checkbox-label-color': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-border-color': '#fafbfc',

  '--theme-bordered-box-background-color': '#263345',
  '--theme-bordered-box-border-color': '#263345',
  '--theme-bordered-box-text-color': '#e9f4fe',

  '--theme-button-primary-background-color': 'rgba(83, 99, 112, 0.8)',
  '--theme-button-primary-background-color-hover': 'rgba(83, 99, 112, 0.7)',
  '--theme-button-primary-background-color-active': '#536370',
  '--theme-button-primary-background-color-disabled': 'rgba(36, 62, 98, 0.3)',
  '--theme-button-primary-text-color': '#e9f4fe',
  '--theme-button-flat-background-color': '#f0f3f5',
  '--theme-button-flat-background-color-hover': '#f3f5f7',
  '--theme-button-flat-background-color-active': '#ebeef0',
  '--theme-button-flat-text-color': '#5e6066',

  '--theme-checkbox-label-color': '#e9f4fe',
  '--theme-checkbox-border-color': '#536370',
  '--theme-checkbox-background-color-checked': '#536370',

  '--theme-choice-tabs-text-color': '#e9f4fe',
  '--theme-choice-tabs-text-color-active': '#e9f4fe',
  '--theme-choice-tabs-bottom-border-color-active': '#e9f4fe',

  '--theme-dialog-input-label-color': '#5e6066',
  '--theme-dialog-input-text-color': '#5e6066',
  '--theme-dialog-input-right-floating-indicator-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-dialog-input-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-dialog-input-error-color': '#ea4c5b',
  '--theme-dialog-switch-label-color': '#5e6066',
  '--theme-dialog-title-color': '#5e6066',
  '--theme-dialog-checkbox-label-color': '#5e6066',
  '--theme-dialog-choice-tabs-text-color': '#5e6066',
  '--theme-dialog-choice-tabs-text-color-active': '#5e6066',
  '--theme-dialog-choice-tabs-bottom-border-color-active': '#5e6066',
  '--theme-dialog-big-button-background-color': '#f1f3f5',
  '--theme-dialog-big-button-border-color': '#d7dce0',
  '--theme-dialog-big-button-label-color': '#5e6066',
  '--theme-dialog-big-button-description-color': '#5e6066',
  '--theme-dialog-separation-border-color': '#dfe4e8',
  '--theme-dialog-input-background-color': '#fafbfc',
  '--theme-dialog-input-border-color': '#c6cdd6',
  '--theme-dialog-input-focus-border-color': '#5e6066',

  '--theme-input-border-color': '#5e6066',
  '--theme-input-label-color': '#e9f4fe',
  '--theme-input-text-color': '#e9f4fe',
  '--theme-input-right-floating-text-color': '#8793a1',
  '--theme-input-placeholder-color': '#8793a1',
  '--theme-input-error-color': '#ea4c5b',
  '--theme-input-remove-color-dark': '#d34452',
  '--theme-input-remove-color-light': '#ea4c5b',
  '--theme-input-remove-color-lighter': '#ec5d6b',
  '--theme-input-remove-color-lightest': '#fac8ce',
  '--theme-input-background-color': '#263345',
  '--theme-input-disabled-background-color': '#cfcfcf',
  '--theme-input-focus-border-color': '#c6cdd6',

  '--theme-main-body-background-color': '#0b1926',
  '--theme-main-body-messages-color': '#e9f4fe',

  '--theme-modal-overlay-background-color': 'rgba(0, 0, 0, 0.4)',
  '--theme-modal-background-color': '#fafbfc',

  '--theme-nav-item-background-color': '#263345',
  '--theme-nav-item-background-color-hover': 'rgba(83, 99, 112, 0.1)',
  '--theme-nav-item-background-color-active': '#536370',
  '--theme-nav-item-text-color': '#9ba6b3',
  '--theme-nav-item-text-color-active': '#e9f4fe',

  '--theme-node-update-background-color': '#0b1926',
  '--theme-node-update-title-color': '#5e6066',
  '--theme-node-update-message-color': '#5e6066',
  '--theme-node-sync-info-message-background-color': '#fafbfc',
  '--theme-node-sync-info-message-text-color': '#5e6066',
  '--theme-node-update-accept-button-background-color': 'rgba(83, 99, 112, 0.6)',
  '--theme-node-update-accept-button-background-color-hover': 'rgba(83, 99, 112, 0.8)',
  '--theme-node-update-accept-button-background-color-active': 'rgba(83, 99, 112, 1)',
  '--theme-node-update-deny-button-background-color': 'rgba(83, 99, 112, 0.3)',
  '--theme-node-update-deny-button-background-color-hover': 'rgba(83, 99, 112, 0.8)',
  '--theme-node-update-deny-button-background-color-active': 'rgba(83, 99, 112, 1)',
  '--theme-node-update-button-text-color': '#fafbfc',

  '--theme-notification-message-background-color': 'rgba(83, 99, 112, 0.8)',
  '--theme-notification-message-text-color': '#fafbfc',

  '--theme-receive-qr-code-color': '#e9f4fe',

  '--theme-settings-body-background-color': '#0b1926',
  '--theme-settings-pane-background-color': '#263345',
  '--theme-settings-pane-border-color': '#263345',
  '--theme-settings-menu-box-background-color': '#263345',
  '--theme-settings-menu-box-border-color': '#263345',
  '--theme-settings-menu-item-text-color': '#cecfd1',
  '--theme-settings-menu-item-text-color-active': '#cecfd1',
  '--theme-settings-menu-item-text-color-enabled-hover': '#8793a1',
  '--theme-settings-menu-item-text-color-disabled': '#7a8691',
  '--theme-settings-menu-item-background-color-active': '#0b1926',
  '--theme-settings-menu-item-left-border-color-active': '#8793a1',
  '--theme-settings-theme-select-title-color': '#5e6066',

  '--theme-sidebar-background-color': '#314259',
  '--theme-sidebar-category-background-color-hover': '#263345',
  '--theme-sidebar-category-background-color-active': '#263345',
  '--theme-sidebar-category-text-color': '#e9f4fe',
  '--theme-sidebar-menu-background-color': '#263345',
  '--theme-sidebar-menu-item-background-color-hover': '#1b2430',
  '--theme-sidebar-menu-item-background-color-active': '#1b2430',
  '--theme-sidebar-menu-item-wallet-name-color': '#e9f4fe',
  '--theme-sidebar-menu-item-wallet-info-color': '#bdc0c1',
  '--theme-sidebar-menu-add-button-background-color-active': '#1b2430',
  '--theme-sidebar-menu-add-button-background-color-hover': '#171f29',
  '--theme-sidebar-menu-add-button-text-color': '#e9f4fe',

  '--theme-staking-background-color': '#0b1926',
  '--theme-staking-content-background-color': '#263345',
  '--theme-staking-content-border-color': '#263345',
  '--theme-staking-font-color-accent': '#cecfd1',
  '--theme-staking-font-color-regular': '#0b1926',

  '--theme-switch-background-color-checked': '#536370',
  '--theme-switch-thumb-color-checked': '#536370',
  '--theme-switch-label-color': '#e9f4fe',

  '--theme-test-environment-label-background-color': '#ab1700',
  '--theme-test-environment-label-text-color': '#fafbfc',

  '--theme-topbar-background-color': '#263345',
  '--theme-topbar-wallet-name-color': '#e9f4fe',
  '--theme-topbar-wallet-info-color': '#e9f4fe',
  '--theme-topbar-layout-body-background-color': '#0b1926',

  '--theme-transactions-list-background-color': '#263345',
  '--theme-transactions-list-border-color': '#263345',
  '--theme-transactions-list-group-date-color': '#7a8691',
  '--theme-transactions-list-item-details-color': '#e9f4fe',
  '--theme-transactions-card-background-color': '#e6ebf2',
  '--theme-transactions-card-income-background-color': '#e6ebf2',
  '--theme-transactions-card-expend-background-color': '#f2e6e6',
  '--theme-transactions-card-exchange-background-color': '#f2e6e6',
  '--theme-transactions-priority-color': '#fff',
  '--theme-transactions-priority-low-background-color': '#542A2B',
  '--theme-transactions-priority-medium-background-color': '#706233',
  '--theme-transactions-priority-heigh-background-color': '#274C2D',
  '--theme-transactions-search-background-color': '#fafbfc',
  '--theme-transactions-icon-type-expend-background-color': '#4f5f7a',
  '--theme-transactions-icon-type-income-background-color': '#3b6956',
  '--theme-transactions-icon-type-exchange-background-color': '#10aca4',

  '--theme-uploader-text-color': '#e9f4fe',
  '--theme-uploader-border-color': '#5e6066',

  '--theme-icon-nav-color': '#9ba6b3',
  '--theme-icon-nav-color-active': '#e9f4fe',
  '--theme-icon-sidebar-color': '#fafbfc',
  '--theme-icon-toggle-menu-color': '#fafbfc',
  '--theme-icon-node-update-notification-arrow-color': '#5e6066',
  '--theme-icon-add-wallet-from-sidebar-color': '#fafbfc',
  '--theme-icon-ada-redemption-attention-color': '#fafbfc',
  '--theme-icon-ada-redemption-success-color': '#fafbfc',
  '--theme-icon-ada-redemption-certificate-color': '#9eabbb',
  '--theme-icon-ada-summary-wallet-amount-symbol-color': '#e9f4fe',
  '--theme-icon-ada-summary-wallet-pending-confirmation-symbol-color': '#e9f4fe',
  '--theme-icon-add-wallet-dialog-big-button-color': '#8a98ab',
  '--theme-icon-copy-address-color': '#8793a1',
  '--theme-icon-address-protected-color': '#8793a1',
  '--theme-icon-back-button-color': '#5e6066',
  '--theme-icon-close-button-color': '#5e6066',
  '--theme-icon-file-upload-color': '#5e6066',
  '--theme-icon-transactions-ada-symbol-color': '#e9f4fe',
  '--theme-icon-syncing-logo-color': '#5e6066',
  '--theme-icon-connecting-logo-color': '#fafbfc',
  '--theme-icon-transaction-type-color': '#fafbfc',

  '--theme-backup-mnemonic-background-color': 'rgba(68, 91, 124, 0.05)',

  '--theme-block-generation-info-color': '#5e6066',

  '--theme-connecting-background-color': '#263345',
  '--theme-connecting-text-color': '#fff',
  '--theme-syncing-text-color': '#5e6066',

  '--theme-error-color': '#ea4c5b',

  '--theme-instructions-text-color': '#5e6066',

  '--theme-label-button-color': '#8793a1',

  '--theme-loading-background-color': '#ebeff2',

  '--theme-mnemonic-background-color': '#e6e9ee',
  '--theme-mnemonic-background-color-hover': '#eaecf1',

  '--theme-send-logs-text-color': '#e9f4fe',

  '--theme-separation-border-color': '#334152',

  '--theme-support-settings-text-color': '#e9f4fe',

  '--theme-terms-of-use-text-color': '#e9f4fe',

  '--theme-wallet-password-switch-label-color': '#5e6066',
};
