export default {
  '--preferred-font': '"Times New Roman", serif',

  '--font-ultralight': 'SFUIDisplay-Ultralight',
  '--font-thin': 'SFUIDisplay-Thin',
  '--font-light': 'SFUIDisplay-Light',
  '--font-regular': 'SFUIDisplay-Regular',
  '--font-medium': 'SFUIDisplay-Medium',
  '--font-semibold': 'SFUIDisplay-Semibold',
  '--font-bold': 'SFUIDisplay-Bold',
  '--font-heavy': 'SFUIDisplay-Heavy',
  '--font-black': 'SFUIDisplay-Black',

  '--theme-input-hint-font': '--font-regular',

  //  ==== BLACK THEME === //
  '--theme-ada-redemption-headline-color': '#5e6066',
  '--theme-ada-redemption-instructions-color': '#5e6066',
  '--theme-ada-redemption-success-overlay-background-color': 'rgba(44, 187, 105, 0.88)',
  '--theme-ada-redemption-success-overlay-border-color': '#fafbfc',
  '--theme-ada-redemption-success-overlay-message-color': '#fafbfc',
  '--theme-ada-redemption-success-overlay-button-text-color': '#fafbfc',
  '--theme-ada-redemption-success-overlay-button-text-color-hover': '#2cbb69',
  '--theme-ada-redemption-success-overlay-button-background-color-hover': '#fafbfc',
  '--theme-ada-redemption-disclaimer-background-color': 'rgba(171, 23, 0, 0.94)',
  '--theme-ada-redemption-disclaimer-text-color': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-background-color': '#ab1700',
  '--theme-ada-redemption-disclaimer-button-text-color': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-background-color-hover': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-text-color-hover': '#ab1700',
  '--theme-ada-redemption-disclaimer-checkbox-color-check': '#fafbfc',
  '--theme-ada-redemption-disclaimer-checkbox-color-checked': '#fafbfc',
  '--theme-ada-redemption-disclaimer-checkbox-color-after': '#ab1700',
  '--theme-ada-redemption-disclaimer-checkbox-label-color': '#fafbfc',
  '--theme-ada-redemption-disclaimer-button-border-color': '#fafbfc',

  '--theme-bordered-box-background-color': '#fafbfc',
  '--theme-bordered-box-border-color': '#c6cdd6',
  '--theme-bordered-box-text-color': '#5e6066',

  '--theme-button-primary-background-color': '#2f9122',
  '--theme-button-primary-background-color-hover': '#59a74e',
  '--theme-button-primary-background-color-active': '#26741b',
  '--theme-button-primary-background-color-disabled': 'rgba(47, 145, 34, 0.3)',
  '--theme-button-primary-text-color': '#fafbfc',
  '--theme-button-flat-background-color': '#f0f3f5',
  '--theme-button-flat-background-color-hover': '#f3f5f7',
  '--theme-button-flat-background-color-active': '#ebeef0',
  '--theme-button-flat-text-color': '#5e6066',

  '--theme-checkbox-label-color': '#5e6066',
  '--theme-checkbox-border-color': '#2cbb69',
  '--theme-checkbox-background-color-checked': '#2cbb69',

  '--theme-choice-tabs-text-color': '#5e6066',
  '--theme-choice-tabs-text-color-active': '#5e6066',
  '--theme-choice-tabs-bottom-border-color-active': '#5e6066',

  '--theme-dialog-input-label-color': '#5e6066',
  '--theme-dialog-input-text-color': '#5e6066',
  '--theme-dialog-input-right-floating-indicator-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-dialog-input-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-dialog-input-error-color': '#de3226',
  '--theme-dialog-switch-label-color': '#5e6066',
  '--theme-dialog-choice-tabs-text-color': '#5e6066',
  '--theme-dialog-choice-tabs-text-color-active': '#5e6066',
  '--theme-dialog-choice-tabs-bottom-border-color-active': '#5e6066',
  '--theme-dialog-checkbox-label-color': '#5e6066',
  '--theme-dialog-big-button-background-color': '#f1f3f5',
  '--theme-dialog-big-button-border-color': '#d7dce0',
  '--theme-dialog-big-button-label-color': '#5e6066',
  '--theme-dialog-big-button-description-color': '#5e6066',
  '--theme-dialog-title-color': '#5e6066',
  '--theme-dialog-separation-border-color': '#dfe4e8',
  '--theme-dialog-input-background-color': '#fafbfc',
  '--theme-dialog-input-focus-border-color': '#5e6066',

  '--theme-input-border-color': '#c6cdd6',
  '--theme-input-label-color': '#5e6066',
  '--theme-input-text-color': '#5e6066',
  '--theme-input-right-floating-text-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-input-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-input-error-color': '#ea4c5b',
  '--theme-input-remove-color-dark': '#d34452',
  '--theme-input-remove-color-light': '#ea4c5b',
  '--theme-input-remove-color-lighter': '#ec5d6b',
  '--theme-input-background-color': '#fafbfc',
  '--theme-input-disabled-background-color': '#cfcfcf',
  '--theme-input-focus-border-color': '#5e6066',

  '--theme-main-body-background-color': '#efefef',
  '--theme-main-body-messages-color': '#5e6066',

  '--theme-modal-overlay-background-color': 'rgba(0, 0, 0, 0.4)',
  '--theme-modal-background-color': '#fafbfc',

  '--theme-nav-item-background-color': '#202225',
  '--theme-nav-item-background-color-hover': 'rgba(250, 251, 252, 0.1)',
  '--theme-nav-item-background-color-active': '#fafbfc',
  '--theme-nav-item-text-color': '#cecfd1',
  '--theme-nav-item-text-color-active': '#5e6066',

  '--theme-node-update-background-color': '--theme-main-body-background-color',
  '--theme-node-update-title-color': '#5e6066',
  '--theme-node-update-message-color': '#5e6066',
  '--theme-node-sync-info-message-background-color': '#fafbfc',
  '--theme-node-sync-info-message-text-color': '#5e6066',
  '--theme-node-update-accept-button-backgroun-color': '#2cbb69',
  '--theme-node-update-accept-button-backgroun-color-hover': 'darken(#2cbb69, 10%)',
  '--theme-node-update-deny-button-backgroun-color': 'rgba(44, 187, 105, 0.3)',
  '--theme-node-update-deny-button-backgroun-color-hover': 'darken(#2cbb69, 10%)',
  '--theme-node-update-button-text-color': '#fafbfc',

  '--theme-notification-message-background-color': 'rgba(47, 145, 34, 0.8)',
  '--theme-notification-message-text-color': '#fafbfc',

  '--theme-settings-body-background-color': '#efefef',
  '--theme-settings-pane-background-color': '#fafbfc',
  '--theme-settings-pane-border-color': '#c6cdd6',
  '--theme-settings-menu-box-background-color': '#fafbfc',
  '--theme-settings-menu-box-border-color': '#c6cdd6',
  '--theme-settings-menu-item-text-color': '#5e6066',
  '--theme-settings-menu-item-text-color-active': '#5e6066',
  '--theme-settings-menu-item-text-color-enabled-hover': '#5e6066',
  '--theme-settings-menu-item-text-color-disabled': '#b3b3b3',
  '--theme-settings-menu-item-background-color-active': '#edf0f3',
  '--theme-settings-menu-item-left-border-color-active': '#2cbb69',
  '--theme-settings-theme-select-title-color': '#5e6066',

  '--theme-sidebar-background-color': '#4a5058',
  '--theme-sidebar-category-background-color-hover': '#34383d',
  '--theme-sidebar-category-background-color-active': '#34383d',
  '--theme-sidebar-category-text-color': '#fafbfc',
  '--theme-sidebar-menu-background-color': '#34383d',
  '--theme-sidebar-menu-item-background-color-hover': '#202225',
  '--theme-sidebar-menu-item-background-color-active': '#202225',
  '--theme-sidebar-menu-item-wallet-name-color': '#fafbfc',
  '--theme-sidebar-menu-item-wallet-info-color': '#bdc0c1',
  '--theme-sidebar-menu-add-button-background-color-active': '#202225',
  '--theme-sidebar-menu-add-button-background-color-hover': 'darken(--theme-sidebar-menu-add-button-background-color-active, 2%)',
  '--theme-sidebar-menu-add-button-text-color': '#fafbfc',

  '--theme-staking-background-color': '--theme-main-body-background-color',
  '--theme-staking-content-background-color': '--theme-settings-pane-background-color',
  '--theme-staking-content-border-color': '--theme-settings-pane-border-color',
  '--theme-staking-font-color-accent': '--theme-settings-menu-item-text-color',
  '--theme-staking-font-color-regular': '--theme-settings-menu-item-text-color-active',

  '--theme-switch-background-color-checked': '#2cbb69',
  '--theme-switch-thumb-color-checked': '#2cbb69',
  '--theme-switch-label-color': '#5e6066',

  '--theme-test-environment-label-background-color': '#ab1700',
  '--theme-test-environment-label-text-color': '#fafbfc',

  '--theme-topbar-background-color': '#202225',
  '--theme-topbar-wallet-name-color': '#fafbfc',
  '--theme-topbar-wallet-info-color': '#fafbfc',
  '--theme-topbar-layout-body-background-color': '#ebeff2',

  '--theme-transactions-list-background-color': '#fafbfc',
  '--theme-transactions-list-border-color': '#c6cdd6',
  '--theme-transactions-list-group-date-color': '#a6a7aa',
  '--theme-transactions-list-item-details-color': '#5e6066',
  '--theme-transactions-card-background-color': '#e6ebf2',
  '--theme-transactions-card-income-background-color': '#e6ebf2',
  '--theme-transactions-card-expend-background-color': '#f2e6e6',
  '--theme-transactions-card-exchange-background-color': '#f2e6e6',
  '--theme-transactions-priority-color': '#fafbfc',
  '--theme-transactions-priority-low-background-color': '#ab1700',
  '--theme-transactions-priority-medium-background-color': '#e6aa00',
  '--theme-transactions-priority-heigh-background-color': '#007600',
  '--theme-transactions-search-background-color': '#fafbfc',

  '--theme-uploader-text-color': '#5e6066',
  '--theme-uploader-border-color': '#c6cdd6',

  '--theme-backup-mnemonic-background-color': 'rgba(68, 91, 124, 0.05)',

  '--theme-block-generation-info-color': '#5e6066',

  '--theme-connecting-background-color': '#345078',

  '--theme-error-color': '#ea4c5b',

  '--theme-instructions-text-color': '#5e6066',

  '--theme-label-button-color': '#5e6066',

  '--theme-loading-background-color': '#ebeff2',

  '--theme-mnemonic-background-color': 'rgba(68, 91, 124, 0.05);',

  '--theme-send-logs-text-color': '#5e6066',

  '--theme-separation-border-color': '#dfe4e8',

  '--theme-support-settings-text-color': '#5e6066',

  '--theme-terms-of-use-text-color': '#5e6066',

  '--theme-wallet-password-switch-label-color': '#5e6066',
};
