env:

  ARTIFACT_BUCKET: s3://ci-output-sink

steps:

  # XXX: `</dev/null turns off any interactive questions from Nix (e.g. accept-flake-config)

  - label: 'daedalus-x86_64-darwin'
    command: 'nix </dev/null run --no-accept-flake-config -L .#packages.x86_64-darwin.buildkitePipeline'
    agents:
      queue: lace
      system: x86_64-darwin

  - label: 'daedalus-aarch64-darwin'
    command: 'nix </dev/null run --no-accept-flake-config -L .#packages.aarch64-darwin.buildkitePipeline'
    env:
      # XXX: avoid Böhm GC segfaults in Nix on aarch64-darwin:
      GC_DONT_GC: 1
    agents:
      queue: lace
      system: aarch64-darwin

  - label: 'daedalus-x86_64-linux'
    command: 'nix </dev/null run --no-accept-flake-config -L .#packages.x86_64-linux.buildkitePipeline'
    agents:
      queue: lace
      system: x86_64-linux

  - label: 'daedalus-x86_64-windows'
    command: 'nix </dev/null run --no-accept-flake-config -L .#packages.x86_64-linux.buildkitePipeline-x86_64-windows'
    agents:
      queue: lace
      system: x86_64-linux
