export const component: string;
export const dialogComponent: string;
export const error: string;
export const infoIcon: string;
export const jpLangTooltipIcon: string;
export const passwordInstructions: string;
export const spendingPasswordField: string;
export const spendingPasswordFields: string;
export const walletName: string;
