// @flow
import type { StorageKey } from '../types/electron-store.types';

export const STORAGE_KEYS: {
  [key: string]: StorageKey,
} = {
  USER_LOCALE: 'USER-LOCALE',
  USER_NUMBER_FORMAT: 'USER-NUMBER-FORMAT',
  USER_DATE_FORMAT_ENGLISH: 'USER-DATE-FORMAT-ENGLISH',
  USER_DATE_FORMAT_JAPANESE: 'USER-DATE-FORMAT-JAPANESE',
  USER_TIME_FORMAT: 'USER-TIME-FORMAT',
  TERMS_OF_USE_ACCEPTANCE: 'TERMS-OF-USE-ACCEPTANCE',
  THEME: 'THEME',
  DATA_LAYER_MIGRATION_ACCEPTANCE: 'DATA-LAYER-MIGRATION-ACCEPTANCE',
  READ_NEWS: 'READ-NEWS',
  WALLETS: 'WALLETS',
  WALLET_MIGRATION_STATUS: 'WALLET-MIGRATION-STATUS',
};
