export const checkIcon: string;
export const clearIcon: string;
export const component: string;
export const externalLink: string;
export const isError: string;
export const isReady: string;
export const message: string;
export const messageWrapper: string;
export const secondaryMessage: string;
