// @flow

export type StorageKey =
  | 'USER-LOCALE'
  | 'USER-NUMBER-FORMAT'
  | 'USER-DATE-FORMAT-ENGLISH'
  | 'USER-DATE-FORMAT-JAPANESE'
  | 'USER-TIME-FORMAT'
  | 'TERMS-OF-USE-ACCEPTANCE'
  | 'THEME'
  | 'DATA-LAYER-MIGRATION-ACCEPTANCE'
  | 'READ-NEWS'
  | 'WALLETS'
  | 'WALLET-MIGRATION-STATUS';
