export const active: string;
export const addWalletButton: string;
export const hideThumb: string;
export const icon: string;
export const scrollbarThumb: string;
export const wallets: string;
export const walletSearchContainer: string;
export const walletSortControls: string;
export const walletSortOffset: string;
