export const component: string;
export const currencyIsFetchingRate: string;
export const currencyLastFetched: string;
export const currencyRate: string;
export const currencySettingsIcon: string;
export const currencySymbol: string;
export const currencyTitle: string;
export const currencyWalletAmount: string;
export const ellipsis: string;
