// @flow
import { createTheme } from '../utils/createTheme';
import type { CreateThemeParams } from '../types';

//  ==== dark-cardano theme config for Daedalus and react-polymorph components === //
export const DARK_CARDANO_THEME_CONFIG = {
  rpAutocomplete: {
    '--rp-autocomplete-bg-color': '#a5a5ad',
    '--rp-autocomplete-border': '1px solid rgba(255, 255, 255, 0.2)',
    '--rp-autocomplete-border-color-opened': 'rgba(255, 255, 255, 0.4)',
    '--rp-autocomplete-input-text-color': '#ffffff',
    '--rp-autocomplete-placeholder-color': '#ffffff80',
    '--rp-autocomplete-selected-word-box-bg-color': '#4ccdcf',
    '--rp-autocomplete-selected-word-text-color': '#0b1926',
    '--rp-autocomplete-selected-words-font-family':
      'NotoSans-Regular, NotoSansCJKjp-Regular',
  },
  rpBubble: {
    '--rp-bubble-bg-color': '#a5a5ad',
    '--rp-bubble-border-color': 'rgba(255, 255, 255, 0.2)',
    '--rp-bubble-border-radius': '2px',
    '--rp-bubble-arrow-bg-color': '#1e1f31',
  },
  rpButton: {
    '--rp-button-bg-color': '#1fc1c3',
    '--rp-button-bg-color-active': '#168789',
    '--rp-button-bg-color-disabled': '#a5e6e7',
    '--rp-button-bg-color-hover': '#4ccdcf',
    '--rp-button-font-family': 'NotoSans-Medium, NotoSansCJKjp-Medium',
    '--rp-button-font-size': '14px',
    '--rp-button-height': '50px',
    '--rp-button-line-height': '20px',
    '--rp-button-padding': '0',
    '--rp-button-text-color': '#0b1926',
    '--rp-button-text-color-disabled': '#0b1926',
    '--rp-button-text-transform': 'none',
    '--rp-button-width': '360px',
  },
  rpCheckbox: {
    '--rp-checkbox-border': '1px solid #1fc1c3',
    '--rp-checkbox-border-color-disabled': '#1fc1c366',
    '--rp-checkbox-check-bg-color': '#1fc1c3',
    '--rp-checkbox-label-text-color': '#ffffff',
    '--rp-checkbox-label-text-color-disabled': '#ffffff4d',
  },
  rpColors: {
    '--rp-theme-color-error': '#ea4c5b',
  },
  rpFonts: {
    '--rp-theme-font-thin': 'NotoSans-Thin, NotoSansCJKjp-Thin',
    '--rp-theme-font-light': 'NotoSans-Light, NotoSansCJKjp-Light',
    '--rp-theme-font-medium': 'NotoSans-Medium, NotoSansCJKjp-Medium',
    '--rp-theme-font-regular': 'NotoSans-Regular, NotoSansCJKjp-Regular',
    '--rp-theme-font-bold': 'NotoSans-Bold, NotoSansCJKjp-Bold',
  },
  rpFormfield: {
    '--rp-formfield-bg-color-disabled': 'none',
    '--rp-formfield-label-text-color': '#ffffff',
    '--rp-formfield-label-text-color-disabled': '#ffffff',
    '--rp-formfield-error-text-color': '#ea4c5b',
    '--rp-formfield-error-text-opacity': '0.75',
  },
  rpInput: {
    '--rp-input-bg-color': '#a5a5ad',
    '--rp-input-bg-color-disabled': '#787983',
    '--rp-input-border-color': 'rgba(255, 255, 255, 0.2)',
    '--rp-input-border-color-disabled': '#ffffff80',
    '--rp-input-border-color-errored': '#ea4c5b',
    '--rp-input-border-color-focus': 'rgba(255, 255, 255, 0.4)',
    '--rp-input-line-height': '22px',
    '--rp-input-padding': '12px 20px',
    '--rp-input-placeholder-color': '#ffffff80',
    '--rp-input-placeholder-color-disabled': '#ffffff80',
    '--rp-input-text-color': '#ffffff',
    '--rp-input-text-color-disabled': '#ffffff80',
  },
  rpModal: {
    '--rp-modal-bg-color': '#a5a5ad',
    '--rp-modal-max-height': '90%',
    '--rp-modal-overlay-bg-color': 'rgba(0, 0, 0, 0.4)',
  },
  rpOptions: {
    '--rp-option-bg-color': '#a5a5ad',
    '--rp-option-bg-color-highlighted': '#1e1f31',
    '--rp-option-border-color': 'rgba(255, 255, 255, 0.2)',
    '--rp-option-checkmark-color': '#ffffff',
    '--rp-option-line-height': '22px',
    '--rp-option-text-color': '#ffffff',
    '--rp-options-border-color': 'rgba(255, 255, 255, 0.2)',
    '--rp-options-shadow': 'none',
  },
  rpSelect: {
    '--rp-select-arrow-bg-color': 'rgba(255, 255, 255, 0.2)',
    '--rp-select-arrow-bg-color-open': 'rgba(255, 255, 255, 0.4)',
    '--rp-select-input-bg-color': '#a5a5ad',
    '--rp-select-input-border-color': 'rgba(255, 255, 255, 0.2)',
    '--rp-select-input-border-color-focus': 'rgba(255, 255, 255, 0.4)',
    '--rp-select-input-text-color': '#ffffff',
    '--rp-select-input-placeholder-color': '#ffffff80',
  },
  rpStepper: {
    '--rp-stepper-bullet-background-color-disabled': '#a5a5ad',
    '--rp-stepper-bullet-border-color': '#1fc1c31a',
    '--rpstepper-bullet-height': '12px',
    '--rpstepper-bullet-width': '12px',
    '--rp-stepper-label-color': '#ffffff',
    '--rp-stepper-label-color-light': '#ffffff4d',
    '--rp-stepper-main-color': '#1fc1c3',
    '--rp-stepper-main-color-light': '#1fc1c31a',
    '--rpstepper-stepper-step-label-bottom-margin': '6px',
    '--rpstepper-steps-bar-color-disabled': '#1fc1c31a',
    '--rpstepper-steps-bar-top-position': '6px',
  },
  rpSwitch: {
    '--rp-switch-bg-color-off': '#1fc1c3',
    '--rp-switch-bg-color-on': '#1fc1c3',
    '--rp-switch-label-margin': '0 30px 0 0',
    '--rp-switch-label-opacity': '0.5',
    '--rp-switch-label-text-color': '#ffffff',
    '--rp-switch-label-width': '100%',
    '--rp-switch-opacity-off': '0.3',
    '--rp-switch-root-margin': '0 0 30px 0',
    '--rp-switch-thumb-bg-color': '#0b1926',
  },
  rpTextArea: {
    '--rp-textarea-bg-color': '#1e1f31',
    '--rp-textarea-bg-color-disabled': '#1e1f3180',
    '--rp-textarea-border': '1px solid rgba(255, 255, 255, 0.2)',
    '--rp-textarea-border-color-disabled': '#ffffff80',
    '--rp-textarea-border-color-errored': '#ea4c5b',
    '--rp-textarea-border-color-focus': 'rgba(255, 255, 255, 0.4)',
    '--rp-textarea-border-radius': '2px',
    '--rp-textarea-line-height': '20px',
    '--rp-textarea-placeholder-color': '#ffffff80',
    '--rp-textarea-resize': 'none',
    '--rp-textarea-text-color': '#ffffff',
  },
  aboutWindow: {
    '--theme-about-window-background-color': '#1fc1c3f5',
    '--theme-about-window-header-bottom-border-color': '#0b19264d',
    '--theme-about-window-daedalus-icon-color': '#0b1926',
    '--theme-about-window-cardano-icon-color': '#0b1926',
    '--theme-about-window-title-varsion-color': '#0b1926',
    '--theme-about-window-title-stroke-color': '#0b1926',
    '--theme-about-window-content-color': '#0b1926',
    '--theme-about-window-content-text-color': '#0b1926',
    '--theme-about-window-content-bottom-border-color': '#0b19264d',
    '--theme-about-window-icon-close-button-color': '#a5a5ad',
    '--theme-about-window-icon-close-hover-background': '#1caeb0',
  },
  adaRedemption: {
    '--theme-ada-redemption-headline-color': '#ffffff',
    '--theme-ada-redemption-instructions-color': '#ffffff',
    '--theme-ada-redemption-success-overlay-background-color': '#1fc1c3',
    '--theme-ada-redemption-success-overlay-border-color': '#0b1926',
    '--theme-ada-redemption-success-overlay-message-color': '#0b1926',
    '--theme-ada-redemption-success-overlay-button-text-color': '#0b1926',
    '--theme-ada-redemption-success-overlay-button-text-color-hover': '#1fc1c3',
    '--theme-ada-redemption-success-overlay-button-background-color-hover':
      '#4ccdcf',
    '--theme-ada-redemption-disclaimer-background-color':
      'rgba(171, 23, 0, 0.94)',
    '--theme-ada-redemption-disclaimer-text-color': '#0b1926',
    '--theme-ada-redemption-disclaimer-checkbox-color-check': '#a5a5ad',
    '--theme-ada-redemption-disclaimer-checkbox-color-checked': '#a5a5ad',
    '--theme-ada-redemption-disclaimer-checkbox-color-after': '#ea4c5b',
    '--theme-ada-redemption-disclaimer-checkbox-label-color': '#0b1926',
    '--theme-ada-redemption-no-wallets-instructions-color': '#ffffff',
    '--theme-ada-redemption-disclaimer-button-border-color': '#a5a5ad',
  },
  blockConsolidation: {
    '--theme-block-consolidation-background-color': '#1fc1c3',
    '--theme-block-consolidation-title-text-color': '#0b1926',
    '--theme-block-consolidation-text-color': '#0b1926',
    '--theme-block-consolidation-text-highlight-color': '#0b1926',
    '--theme-block-consolidation-epochs-text-color': '#1fc1c3',
    '--theme-block-consolidation-indicator-text-color': '#0b1926',
    '--theme-block-consolidation-indicator-container-background-color':
      'rgba(0, 0, 0, 0.1)',
    '--theme-block-consolidation-indicator-epochs-behind-background-color-1':
      '#a5a5ad',
    '--theme-block-consolidation-indicator-epochs-behind-background-color-2':
      '#1fc1c3',
    '--theme-block-consolidation-stripe-dark-1-background-color': '#1e1f31',
    '--theme-block-consolidation-stripe-dark-2-background-color': '#1b1c2c',
    '--theme-block-consolidation-stripe-light-1-background-color': '#a5e6e7',
    '--theme-block-consolidation-stripe-light-2-background-color': '#4b4c5a',
    '--theme-block-consolidation-button-background-color': '#1caeb0',
    '--theme-block-consolidation-button-background-color-hover': '#a5a5ad',
    '--theme-block-consolidation-button-icon-color': '#0b1926',
    '--theme-block-consolidation-button-icon-color-hover': '#1fc1c3',
    '--theme-block-consolidation-button-text-color-hover': '#1fc1c3',
    '--theme-block-consolidation-button-border-color': '#a5a5ad',
  },
  body: {
    '--theme-main-body-background-color': '#1e1f31',
    '--theme-main-body-messages-color': '#ffffff',
  },
  borderedBox: {
    '--theme-bordered-box-background-color': '#a5a5ad',
    '--theme-bordered-box-border': '1px solid rgba(255, 255, 255, 0.2)',
    '--theme-bordered-box-text-color': '#ffffff',
  },
  button: {
    '--theme-button-spinner-color': '#a5a5ad',
    '--theme-label-button-color': '#ffffff',
  },
  buttonAttention: {
    '--theme-button-attention-background-color': '#ea4c5b',
    '--theme-button-attention-background-color-hover': '#ee707c',
    '--theme-button-attention-background-color-active': '#a43540',
    '--theme-button-attention-background-color-disabled': '#fbdbde',
    '--theme-button-attention-text-color': '#0b1926',
    '--theme-button-attention-text-color-disabled': '#0b1926',
    '--theme-button-attention-outline-color': '#f2949d',
  },
  buttonDisclaimer: {
    '--theme-button-disclaimer-background-color': '#ab1700',
    '--theme-button-disclaimer-background-color-hover': '#fafbfc',
    '--theme-button-disclaimer-background-color-active': '#fafbfc',
    '--theme-button-disclaimer-background-color-disabled':
      'rgba(171, 23, 0, .3)',
    '--theme-button-disclaimer-text-color-disabled': 'rgba(250, 251, 252, .3)',
    '--theme-button-disclaimer-text-color': '#fafbfc',
    '--theme-button-disclaimer-outline-color': 'rgba(250, 251, 252, .3)',
    '--theme-button-disclaimer-border-color': '#fafbfc',
    '--theme-button-disclaimer-border-color-disabled':
      'rgba(250, 251, 252, .3)',
  },
  buttonFlat: {
    '--theme-button-flat-background-color': '#4b4c5a',
    '--theme-button-flat-background-color-hover': '#787983',
    '--theme-button-flat-background-color-active': '#1e1f31',
    '--theme-button-flat-background-color-disabled': '#787983',
    '--theme-button-flat-text-color-disabled': '#ffffff',
    '--theme-button-flat-text-color': '#ffffff',
    '--theme-button-flat-outline-color': '#1b1c2c',
  },
  buttonPrimary: {
    '--theme-button-primary-background-color': '#1fc1c3',
    '--theme-button-primary-background-color-hover': '#4ccdcf',
    '--theme-button-primary-background-color-active': '#168789',
    '--theme-button-primary-background-color-disabled': '#a5e6e7',
    '--theme-button-primary-text-color-disabled': '#0b1926',
    '--theme-button-primary-text-color': '#0b1926',
    '--theme-button-primary-outline-color': '#4ccdcf',
  },
  connecting: {
    '--theme-connecting-background-color': '#1fc1c3',
    '--theme-connecting-text-color': '#0b1926',
  },
  dataMigration: {
    '--theme-data-migration-layer-background-color': '#1fc1c3',
    '--theme-data-migration-layer-box-shadow-color': '#1fc1c3',
    '--theme-data-migration-layer-button-background-color-hover': '#1e1f31',
    '--theme-data-migration-layer-text-color': '#0b1926',
    '--theme-data-migration-layer-text-opacity-color': '#0b1926',
  },
  delegationSetupWizard: {
    '--theme-delegation-steps-activation-steps-indicator-color': '#ffffff',
    '--theme-delegation-steps-activation-description-color': '#ffffffcc',
    '--theme-delegation-steps-activation-fees-label-color': '#ffffff',
    '--theme-delegation-steps-activation-fees-amount-color': '#ea4c5b',
    '--theme-delegation-steps-activation-address-value-color': '#ffffff',
    '--theme-delegation-steps-choose-stake-pool-checkmark-icon-color':
      'rgba(255, 255, 255, 0.2)',
    '--theme-delegation-steps-choose-stake-pool-delegated-pools-label-color':
      '#ffffff',
    '--theme-delegation-steps-choose-stake-pool-slug-color':
      'rgba(255, 255, 255, 0.2)',
    '--theme-delegation-steps-choose-stake-pool-select-box-placeholder-color':
      'rgba(255, 255, 255, 0.2)',
    '--theme-delegation-steps-choose-stake-pool-selected-checkmark-icon-color':
      '#0b1926',
    '--theme-delegation-steps-choose-stake-pool-selected-slug-color': '#0b1926',
    '--theme-delegation-steps-choose-stake-pool-title-color': '#ffffffcc',
    '--theme-delegation-steps-choose-stake-pool-tooltip-arrow-color':
      '#ffffffe6',
    '--theme-delegation-steps-choose-stake-pool-tooltip-background-color':
      '#ffffffe6',
    '--theme-delegation-steps-choose-stake-pool-tooltip-box-shadow':
      '0 5px 20px 0 rgba(0, 0, 0, 0.25)',
    '--theme-delegation-steps-choose-stake-pool-tooltip-description-color':
      '#0b1926',
    '--theme-delegation-steps-choose-stake-pool-tooltip-slug-color':
      '#ffffff99',
    '--theme-delegation-steps-choose-stake-pool-tooltip-table-label-color':
      '#0b1926',
    '--theme-delegation-steps-choose-stake-pool-tooltip-table-value-color':
      '#0b1926',
    '--theme-delegation-steps-choose-stake-pool-tooltip-title-color': '#0b1926',
    '--theme-delegation-steps-choose-stake-pool-tooltip-url-color': '#85b6f9',
    '--theme-delegation-steps-choose-wallet-custom-value-color': '#ffffff',
    '--theme-delegation-steps-choose-wallet-description-color': '#ffffffcc',
    '--theme-delegation-steps-choose-wallet-description-highlighted-color':
      '#ffffff',
    '--theme-delegation-steps-choose-wallet-error-message-color': '#ea4c5b',
    '--theme-delegation-steps-choose-wallet-error-message-light-color':
      '#ea4c5bb3',
    '--theme-delegation-steps-choose-wallet-error-select-options-color':
      '#ffffff',
    '--theme-delegation-steps-choose-wallet-steps-indicator-color': '#ffffff',
    '--theme-delegation-steps-confirmation-steps-indicator-color': '#ffffff',
    '--theme-delegation-steps-confirmation-description-color': '#ffffffcc',
    '--theme-delegation-steps-confirmation-fees-label-color': '#ffffff',
    '--theme-delegation-steps-confirmation-fees-amount-color': '#ea4c5b',
    '--theme-delegation-steps-intro-content-text-color': '#ffffffcc',
    '--theme-delegation-steps-intro-divider-border-color':
      'rgba(255, 255, 255, 0.2)',
    '--theme-delegation-steps-intro-link-color': '#1fc1c3',
    '--theme-delegation-steps-intro-list-label-color': '#ffffff',
    '--theme-delegation-steps-intro-list-numbers-color': '#ffffff',
    '--theme-delegation-steps-intro-list-optional-label-color': '#ffffff80',
    '--theme-delegation-steps-not-available-description-text-color':
      '#ffffffcc',
    '--theme-delegation-steps-not-available-description-highlight-text-color':
      '#ffffff',
    '--theme-delegation-steps-not-available-icon-color': '#ffffff',
    '--theme-delegation-steps-not-available-subtitle-text-color': '#ffffff',
  },
  dialog: {
    '--theme-dialog-choice-tabs-text-color': '#ffffff',
    '--theme-dialog-choice-tabs-text-color-active': '#ffffff',
    '--theme-dialog-choice-tabs-bottom-border-color-active':
      'rgba(255, 255, 255, 0.4)',
    '--theme-dialog-big-button-background-color': '#a5a5ad',
    '--theme-dialog-big-button-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-dialog-big-button-label-color': '#ffffff',
    '--theme-dialog-big-button-description-color': '#ffffff',
    '--theme-dialog-title-color': '#ffffff',
    '--theme-dialog-text-color': '#ffffff',
    '--theme-dialog-border-color': 'rgba(255, 255, 255, 0.2)',
  },
  errors: {
    '--theme-color-error': '#ea4c5b',
  },
  fonts: {
    '--font-ultralight': 'NotoSans-ExtraLight, NotoSansCJKjp-Thin',
    '--font-thin': 'NotoSans-Thin, NotoSansCJKjp-Thin',
    '--font-light': 'NotoSans-Light, NotoSansCJKjp-Light',
    '--font-regular': 'NotoSans-Regular, NotoSansCJKjp-Regular',
    '--font-medium': 'NotoSans-Medium, NotoSansCJKjp-Medium',
    '--font-semibold': 'NotoSans-SemiBold, NotoSansCJKjp-Medium',
    '--font-bold': 'NotoSans-Bold, NotoSansCJKjp-Bold',
    '--font-heavy': 'NotoSans-ExtraBold, NotoSansCJKjp-Black',
    '--font-black': 'NotoSans-Black, NotoSansCJKjp-Black',
    '--font-mono': 'SFMono-Light',
  },
  icon: {
    '--theme-icon-nav-color': '#0b1926',
    '--theme-icon-nav-color-active': '#ffffff',
    '--theme-icon-sidebar-color': '#1e1f31',
    '--theme-icon-toggle-menu-color': '#1e1f31',
    '--theme-icon-node-update-notification-arrow-color': '#ffffff',
    '--theme-icon-add-wallet-from-sidebar-color': '#0b1926',
    '--theme-icon-ada-redemption-attention-color': '#0b1926',
    '--theme-icon-ada-redemption-success-color': '#ffffff',
    '--theme-icon-ada-redemption-certificate-color': '#ffffff',
    '--theme-icon-ada-redemption-no-wallets': '#ffffff',
    '--theme-icon-ada-summary-wallet-amount-symbol-color': '#ffffff',
    '--theme-icon-ada-summary-wallet-pending-confirmation-symbol-color':
      '#ffffff',
    '--theme-icon-add-wallet-dialog-big-button-color': '#181927',
    '--theme-icon-back-button-color': '#ffffff',
    '--theme-icon-close-button-color': '#ffffff',
    '--theme-icon-connecting-logo-color': '#0b1926',
    '--theme-icon-copy-address-color': '#ffffff',
    '--theme-icon-delegation-center-no-wallets': '#ffffff',
    '--theme-icon-file-upload-color': '#ffffff',
    '--theme-icon-syncing-logo-color': '#ffffff',
    '--theme-icon-transactions-ada-symbol-color': '#ffffff',
    '--theme-icon-transaction-type-color': '#fafbfc',
  },
  input: {
    '--theme-input-background-color': '#a5a5ad',
    '--theme-input-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-input-focus-border-color': 'rgba(255, 255, 255, 0.4)',
    '--theme-input-hint-font': 'NotoSans-Regular, NotoSansCJKjp-Regular',
    '--theme-input-label-color': '#ffffff',
    '--theme-input-placeholder-color': '#ffffff80',
    '--theme-input-remove-color-light': '#ea4c5b',
    '--theme-input-right-floating-text-color': '#ffffff80',
    '--theme-input-text-color': '#ffffff',
  },
  link: {
    '--theme-link-main-color': '#1fc1c3',
  },
  loading: {
    '--theme-loading-background-color': '#1e1f31',
    '--theme-loading-no-disk-space-background-color': '#1e1f31',
    '--theme-loading-no-disk-space-text-color': '#ffffff',
    '--theme-loading-no-disk-space-attention-icon-color': '#ffffff',
    '--theme-loading-status-icons-on-color': '#2dc06c',
    '--theme-loading-status-icons-off-color': '#ea4c5b',
    '--theme-loading-status-icons-unloaded-loading-color': '#ffffff',
    '--theme-loading-status-icons-unloaded-syncing-color': '#ffffff',
    '--theme-loading-status-icons-tooltip-color': '#ffffff',
    '--theme-loading-spinner-color': '#ffffff',
  },
  manualUpdate: {
    '--theme-manual-update-overlay-background-color': '#1fc1c3f5',
    '--theme-manual-update-overlay-button-background-color': '#1caeb0',
    '--theme-manual-update-overlay-button-background-color-hover': '#0b1926',
    '--theme-manual-update-overlay-button-icon-color': '#0b1926',
    '--theme-manual-update-overlay-button-icon-color-hover': '#1fc1c3',
    '--theme-manual-update-overlay-button-text-color-hover': '#1fc1c3',
    '--theme-manual-update-overlay-button-border-color': '#0b1926',
    '--theme-manual-update-overlay-text-color': '#0b1926b3',
    '--theme-manual-update-overlay-text-highlight-color': '#0b1926',
    '--theme-manual-update-overlay-title-text-color': '#0b1926',
    '--theme-manual-update-overlay-button-label-color': '#0b1926',
  },
  mnemonic: {
    '--theme-mnemonic-background-color': '#1e1f31',
    '--theme-mnemonic-background-color-hover': '#1b1c2c',
    '--theme-backup-mnemonic-background-color': '#4b4c5a',
  },
  modal: {
    '--theme-modal-overlay-background-color': 'rgba(0, 0, 0, 0.4)',
  },
  navDropdown: {
    '--theme-nav-dropdown-item-text-color': '#ffffff',
    '--theme-nav-dropdown-item-background-color': '#a5a5ad',
    '--theme-nav-dropdown-item-background-color-hover': '#1e1f3112',
    '--theme-nav-dropdown-item-color-hover': '#ffffff',
  },
  navItem: {
    '--theme-nav-item-background-color': '#168789',
    '--theme-nav-item-background-color-active': '#a5a5ad',
    '--theme-nav-item-background-color-hover': '#199a9c',
    '--theme-nav-item-text-color': '#0b1926',
    '--theme-nav-item-text-color-active': '#ffffff',
  },
  network: {
    '--theme-network-window-background-color': '#1fc1c3f5',
    '--theme-network-window-text-color': '#0b1926',
    '--theme-network-window-icon-close-hover-background': '#1caeb0',
    '--theme-network-window-red-color': '#f06e05',
    '--theme-network-window-green-color': '#05f079',
    '--theme-network-window-white-color': '#0b1926',
    '--theme-network-window-transparent-color': 'transparent',
    '--theme-network-window-border-color': '#0b1926b3',
    '--theme-network-window-button-text-color': '#0b1926',
    '--theme-network-window-button-background-color': '#a5e6e766',
    '--theme-network-window-button-background-color-hover': '#a5e6e799',
    '--theme-network-window-button-background-color-active': '#a5e6e7cc',
  },
  nodeUpdate: {
    '--theme-node-update-background-color': '#1e1f31',
    '--theme-node-update-title-color': '#ffffff',
    '--theme-node-update-message-color': '#ffffff',
    '--theme-node-sync-info-message-background-color': '#1e1f31',
    '--theme-node-sync-info-message-text-color': '#ffffff',
    '--theme-node-update-accept-button-background-color': '#1fc1c3',
    '--theme-node-update-accept-button-background-color-hover': '#4ccdcf',
    '--theme-node-update-accept-button-background-color-active': '#168789',
    '--theme-node-update-deny-button-background-color': '#1fc1c3',
    '--theme-node-update-deny-button-background-color-hover': '#4ccdcf',
    '--theme-node-update-deny-button-background-color-active': '#168789',
    '--theme-node-update-button-text-color': '#0b1926',
  },
  notification: {
    '--theme-notification-message-background-color': '#1fc1c3f2',
    '--theme-notification-message-text-color': '#0b1926',
    '--theme-legacy-badge-background-color': '#d34452',
    '--theme-legacy-notification-background-color': '#ab2712',
    '--theme-legacy-notification-learn-more-button-text-color': '#0b1926',
    '--theme-legacy-notification-learn-more-button-background-color':
      '#1e1f3133',
    '--theme-legacy-notification-learn-more-button-background-color-hover':
      '#1e1f314d',
    '--theme-legacy-notification-learn-more-button-background-color-active':
      '#1e1f3166',
    '--theme-legacy-notification-move-button-text-color': '#ab2712',
    '--theme-legacy-notification-move-button-background-color': '#0b1926',
    '--theme-legacy-notification-move-button-background-color-hover':
      '#1e1f31e6',
    '--theme-legacy-notification-move-button-background-color-active':
      '#1e1f31cc',
    '--theme-legacy-notification-title-color': '#0b1926',
    '--theme-legacy-notification-description-color': '#0b1926',
  },
  paperWallet: {
    '--theme-paper-wallet-create-certificate-dialog-explorer-link-color':
      '#1fc1c3',
    '--theme-paper-wallet-create-certificate-dialog-explorer-link-background-color':
      '#0b1926',
  },
  progressBar: {
    '--theme-progress-bar-background-color': '#4b4c5a4d',
    '--theme-progress-bar-foreground-color': '#4b4c5ab3',
  },
  receiveQRCode: {
    '--theme-receive-qr-code-background-color': 'transparent',
    '--theme-receive-qr-code-foreground-color': '#000',
  },
  reportIssue: {
    '--theme-report-issue-button-background-color': '#1fc1c3',
    '--theme-report-issue-button-background-color-hover': '#4ccdcf',
    '--theme-report-issue-button-background-color-active': '#168789',
    '--theme-report-issue-connecting-background-color': '#1e1f31',
    '--theme-report-issue-icon-color': '#1e1f31',
    '--theme-report-issue-connecting-text-color': '#ffffff',
    '--theme-report-issue-syncing-background-color': '#1e1f31',
    '--theme-report-issue-syncing-text-color': '#ffffff',
    '--theme-report-issue-syncing-download-logs-text-color': '#ffffff',
    '--theme-report-issue-syncing-download-logs-text-color-connecting':
      '#ffffff',
  },
  scrollbar: {
    '--theme-scrollbar-thumb-background': '#181927',
  },
  sendConfirmation: {
    '--theme-send-confirmation-dialog-send-values-color': '#ea4c5b',
  },
  settings: {
    '--theme-settings-body-background-color': '#1e1f31',
    '--theme-settings-pane-background-color': '#a5a5ad',
    '--theme-settings-pane-border': '1px solid rgba(255, 255, 255, 0.2)',
    '--theme-settings-menu-box-background-color': '#a5a5ad',
    '--theme-settings-menu-box-border': '1px solid rgba(255, 255, 255, 0.2)',
    '--theme-settings-menu-item-text-color': '#ffffff',
    '--theme-settings-menu-item-text-color-active': '#ffffff',
    '--theme-settings-menu-item-text-color-disabled': '#ffffff80',
    '--theme-settings-menu-item-background-color-active': '#1e1f31',
    '--theme-settings-menu-item-left-border-color-active': '#1fc1c3',
    '--theme-settings-theme-select-title-color': '#ffffff',
  },
  sidebar: {
    '--theme-sidebar-background-color': '#1fc1c3',
    '--theme-sidebar-category-background-color-hover': '#1caeb0',
    '--theme-sidebar-category-background-color-active': '#199a9c',
    '--theme-sidebar-category-text-color': '#0b1926',
    '--theme-sidebar-menu-background-color': '#199a9c',
    '--theme-sidebar-menu-item-background-color-hover': '#168789',
    '--theme-sidebar-menu-item-background-color-active': '#168789',
    '--theme-sidebar-menu-item-wallet-name-color': '#0b1926',
    '--theme-sidebar-menu-item-wallet-info-color': '#0b1926',
    '--theme-sidebar-menu-add-button-background-color': '#168789',
    '--theme-sidebar-menu-add-button-background-color-active': '#168789a8',
    '--theme-sidebar-menu-add-button-background-color-hover': '#168789a8',
    '--theme-sidebar-menu-add-button-text-color': '#0b1926',
  },
  stakePools: {
    '--theme-staking-stake-pools-title-color': '#ffffff',
    '--theme-staking-stake-pools-search-button-color': '#ffffff',
    '--theme-staking-stake-pool-background-color': '#a5a5ad',
    '--theme-staking-stake-pool-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-staking-stake-pool-glow-color': '#a5e6e7',
    '--theme-staking-stake-pools-search-icon-color': '#ffffff',
    '--theme-staking-stake-pool-selected-background-color': '#5da377',
    '--theme-staking-stake-pool-selected-checkmark-icon-color': '#0b1926',
    '--theme-staking-stake-pool-selected-slug-color': '#0b1926',
    '--theme-staking-stake-pool-slug-color': '#ffffff',
    '--theme-staking-stake-pool-retirement-background-color': '#ea4c5b',
    '--theme-staking-stake-pool-tooltip-background-color': '#a5a5adf7',
    '--theme-staking-stake-pool-tooltip-border-color':
      'rgba(255, 255, 255, 0.2)',
    '--theme-staking-stake-pool-tooltip-shadow-color': 'rgba(0, 0, 0, 0.25)',
    '--theme-staking-stake-pool-tooltip-text-color': '#ffffff',
    '--theme-staking-stake-pool-tooltip-link-color': '#1caeb0',
    '--theme-staking-stake-pool-tooltip-table-title-color': '#ffffff',
    '--theme-staking-stake-pool-tooltip-table-param-color': '#ffffff',
    '--theme-staking-stake-pool-tooltip-retirement-text-color': '#fafbfc',
    '--theme-staking-stake-pool-tooltip-retirement-background-color':
      '#ea4c5b4d',
    '--theme-staking-stake-pool-tooltip-delegate-button-background-color':
      '#1fc1c3',
    '--theme-staking-stake-pool-tooltip-delegate-button-hover-background-color':
      '#4ccdcf',
    '--theme-staking-stake-pool-tooltip-delegate-button-active-background-color':
      '#168789',
    '--theme-staking-stake-pool-tooltip-delegate-button-text-color': '#0b1926',
    '--theme-staking-stake-pool-tooltip-delegate-button-inverse-text-color':
      '#0b1926',
    '--theme-staking-stake-pool-tooltip-delegate-button-border-color':
      'transparent',
  },
  staking: {
    '--theme-staking-content-background-color': '#a5a5ad',
    '--theme-staking-content-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-staking-font-color-accent': 'rgba(255, 255, 255, 0.4)',
    '--theme-staking-font-color-regular': '#ffffff',
    '--theme-staking-font-color-light': '#ffffffb3',
    '--theme-staking-font-color-lighter': '#ffffff80',
    '--theme-staking-table-head-background-color': '#1e1f31',
    '--theme-staking-table-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-staking-link-color': '#1fc1c3',
    '--theme-staking-link-color-light': '#4ccdcf',
    '--theme-staking-progress-bar-background-color': '#1e1f31',
    '--theme-staking-progress-stripe-dark-1-background-color': '#1caeb0',
    '--theme-staking-progress-stripe-dark-2-background-color': '#1fc1c3',
    '--theme-staking-table-body-highlighted-text-color': '#1caeb0',
    '--theme-staking-info-learn-more-button-color': '#a5a5ad',
    '--theme-staking-info-learn-more-icon-color': '#0b1926',
    '--theme-staking-learn-more-button-color': '#a5a5ad',
    '--theme-staking-learn-more-icon-color': '#0b1926',
    '--theme-staking-donut-ring-completed-color': '#ea4c5b',
    '--theme-staking-donut-ring-remaining-color': '#fbdbde',
    '--theme-staking-wallet-row-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-staking-dropdown-item-text-color-hover': '#ffffff',
    '--theme-staking-dropdown-item-background-color': '#a5a5ad',
    '--theme-staking-dropdown-item-background-color-hover': '#1e1f311a',
    '--theme-staking-delegation-center-gear-icon-fill-color': '#ffffff80',
    '--theme-staking-delegation-center-gear-icon-fill-color-active': '#ffffff',
    '--theme-staking-delegation-center-no-wallets-instructions-color':
      '#ffffff',
  },
  support: {
    '--theme-support-settings-item-color': '#ffffff',
    '--theme-support-settings-link-color': '#1fc1c3',
    '--theme-support-settings-text-color': '#ffffff',
  },
  syncing: {
    '--theme-syncing-background-color': '#1e1f31',
    '--theme-syncing-text-color': '#ffffff',
  },
  systemError: {
    '--theme-system-error-overlay-attention-icon-color': '#0b1926',
    '--theme-system-error-overlay-background-color': '#ea4c5b',
    '--theme-system-error-overlay-support-link-icon-color': '#0b1926',
    '--theme-system-error-overlay-text-color': '#0b1926',
  },
  tabs: {
    '--theme-choice-tabs-text-color': '#ffffff',
    '--theme-choice-tabs-text-color-active': '#ffffff',
    '--theme-choice-tabs-bottom-border-color-active': '#ffffff',
  },
  testEnvironment: {
    '--theme-test-environment-label-background-color': '#ab1700',
    '--theme-test-environment-label-text-color': '#0b1926',
  },
  topBar: {
    '--theme-topbar-background-color': '#168789',
    '--theme-topbar-layout-body-background-color': '#1fc1c3',
    '--theme-topbar-wallet-name-color': '#0b1926',
    '--theme-topbar-wallet-info-color': '#0b1926',
  },
  transactions: {
    '--theme-transactions-list-background-color': '#a5a5ad',
    '--theme-transactions-list-border-color': 'rgba(255, 255, 255, 0.2)',
    '--theme-transactions-list-group-date-color': '#ffffff',
    '--theme-transactions-list-item-details-color': '#ffffff',
    '--theme-transactions-state-failed-background-color': '#1b1c2c',
    '--theme-transactions-state-failed-text-color': '#ffffff',
    '--theme-transactions-state-pending-background-color': '#1b1c2c',
    '--theme-transactions-state-pending-stripes-color': '#181927',
    '--theme-transactions-priority-color': '#1e1f31',
    '--theme-transactions-priority-low-background-color': '#d34452',
    '--theme-transactions-priority-medium-background-color': '#e6aa00',
    '--theme-transactions-priority-high-background-color': '#007600',
    '--theme-transactions-search-background-color': '#1e1f31',
    '--theme-transactions-icon-type-expend-background-color': '#84a2d2',
    '--theme-transactions-icon-type-income-background-color': '#2dc06c',
    '--theme-transactions-icon-type-exchange-background-color': '#10aca4',
    '--theme-transactions-icon-type-failed-background-color': '#ee707c',
    '--theme-transactions-arrow-stroke-color': '#ffffff',
  },
  uploader: {
    '--theme-uploader-text-color': '#ffffff',
    '--theme-uploader-border-color': 'rgba(255, 255, 255, 0.2)',
  },
  utxo: {
    '--theme-utxo-background-color': '#1e1f3180',
    '--theme-utxo-title-text-color': '#ffffff',
    '--theme-utxo-title-description-color': '#ffffffb3',
    '--theme-utxo-bar-color': '#1caeb080',
    '--theme-utxo-label-text-color': '#ffffff73',
    '--theme-utxo-tick-text-color': '#ffffff73',
    '--theme-utxo-cursor-background-color': '#a5e6e733',
    '--theme-utxo-tooltip-background-color': '#151622',
    '--theme-utxo-tooltip-shadow-color': 'rgba(0, 0, 0, 0.18)',
    '--theme-utxo-tooltip-text-color': '#0b1926',
  },
};

const DARK_CARDANO_THEME_PARAMS: CreateThemeParams = {
  config: DARK_CARDANO_THEME_CONFIG,
};

export default createTheme(DARK_CARDANO_THEME_PARAMS);
