export const component: string;
export const isLoading: string;
export const leftContent: string;
export const listTitle: string;
export const loadingBlockWrapper: string;
export const rotatingSpinner: string;
export const smashSettings: string;
export const smashSettingsIcon: string;
export const tinySpinner: string;
