export const component: string;
export const firstInGroup: string;
export const groupDate: string;
export const lastInGroup: string;
export const preloadingBlockWrapper: string;
export const showMoreTransactionsButton: string;
export const syncingTransactionsText: string;
export const syncingTransactionsWrapper: string;
export const transaction: string;
