export const component: string;
export const infoIcon: string;
export const jpLangTooltipIcon: string;
export const passwordInstructions: string;
export const passwordSectionDescription: string;
export const passwordSectionLabel: string;
export const spendingPasswordField: string;
export const spendingPasswordFields: string;
export const spendingPasswordWrapper: string;
