export const active: string;
export const activeIcon: string;
export const component: string;
export const container: string;
export const hasNotification: string;
export const icon: string;
export const label: string;
export const normal: string;
export const normalIcon: string;
