flags: {}

extra-package-dbs: []

allow-newer: true
resolver: lts-11.1

nix:
    packages: [gmp,git]

packages:
- .
extra-deps:
- git: https://github.com/dhall-lang/dhall-json
  commit: d6adaa265dcf8ab5899396b05d612b2d8092dca4

- git: https://github.com/input-output-hk/haskell-nsis.git
  commit: 020e61eced93eaa6ab86ac603617e93aa6bf5af0
