flags: {}

extra-package-dbs: []

packages:
  - location: .
  - location:
      git: https://github.com/jmitchell/nsis.git
      commit: 0658f28beb62d023655dd285a07fb9e3fdab416b
    extra-dep: true

resolver: lts-8.4

nix:
    packages: [gmp,git]
