export const DEFAULT_TIMEOUT = 20000;
export const rewardsMnemonics = [
  ['awkward', 'electric', 'strong', 'early', 'rose', 'abuse', 'mutual', 'limit', 'ketchup', 'child', 'limb', 'exist', 'hurry', 'business', 'whisper'],
  ['blood', 'limit', 'pumpkin', 'fringe', 'order', 'trick', 'answer', 'festival', 'ethics', 'educate', 'luggage', 'dinner', 'record', 'fox', 'truth'],
  ['bridge', 'joke', 'jeans', 'width', 'social', 'banner', 'visit', 'enlist', 'reason', 'hand', 'license', 'subway', 'butter', 'render', 'absent'],
  ['bless', 'turkey', 'install', 'across', 'bronze', 'check', 'true', 'icon', 'treat', 'that', 'tuition', 'flush', 'panther', 'powder', 'ecology'],
  ['trick', 'razor', 'bicycle', 'front', 'hollow', 'liberty', 'swift', 'coconut', 'pull', 'raccoon', 'level', 'woman', 'awful', 'sound', 'swarm'],
];
export const balanceMnemonics = [
  ["surface", "light", "ridge", "alter", "reflect", "digital", "field", "sibling", "moon", "giant", "target", "bleak"],
  ["firm", "scare", "trap", "reopen", "window", "govern", "truck", "negative", "fragile", "share", "setup", "coral"],
  ["zero", "heart", "develop", "wolf", "salute", "parade", "supreme", "pigeon", "fragile", "glue", "manual", "cloth"],
  ["mobile", "phone", "apple", "reduce", "organ", "since", "grace", "song", "pole", "heavy", "speak", "danger"],
  ["vibrant", "verb", "entry", "record", "sketch", "aspect", "ensure", "true", "caution", "long", "suggest", "draft"],
  ["diary", "setup", "wire", "claim", "tattoo", "street", "slice", "skin", "neck", "sunset", "frame", "tip"],
  ["radar", "tail", "much", "accuse", "unknown", "hat", "olympic", "reflect", "surface", "child", "mammal", "pigeon"],
  ["surprise", "shed", "sibling", "pact", "display", "mean", "game", "frog", "citizen", "wing", "honey", "faith"],
  ["child", "divorce", "warm", "deal", "fever", "trial", "nurse", "pencil", "number", "whisper", "sword", "donate"],
  ["arch", "answer", "wood", "decide", "slim", "utility", "logic", "board", "pitch", "also", "rug", "party"],
  ["liberty", "grunt", "west", "lyrics", "surge", "dance", "empower", "twice", "grab", "luxury", "banner", "gun"],
  ["hawk", "cram", "marriage", "monkey", "cost", "unaware", "bind", "pink", "before", "point", "february", "place"],
  ["metal", "steak", "pave", "latin", "eagle", "deal", "worry", "enable", "chalk", "cry", "boil", "oblige"],
  ["family", "sister", "feature", "divide", "agent", "village", "muscle", "fat", "answer", "crop", "upset", "light"],
  ["lesson", "obey", "garbage", "slab", "tomorrow", "fall", "scrub", "smart", "joke", "syrup", "meadow", "cram"],
  ["hood", "giant", "road", "buffalo", "eight", "recycle", "boat", "cup", "update", "empower", "popular", "baby"],
  ["mouse", "clay", "monitor", "proof", "nice", "screen", "toast", "flat", "mother", "indicate", "engage", "kick"],
  ["mixed", "fancy", "shop", "across", "clay", "become", "stadium", "biology", "bulb", "device", "drive", "quote"],
  ["retreat", "typical", "program", "rice", "warfare", "first", "scrap", "path", "believe", "drift", "flock", "mushroom"],
  ["project", "stove", "sample", "cupboard", "long", "comic", "piano", "caution", "toward", "sword", "coach", "protect"],
  ["picture", "lock", "bargain", "cactus", "chicken", "enjoy", "faculty", "script", "hospital", "liberty", "sand", "patch"],
  ["mention", "dog", "insect", "modify", "attitude", "century", "little", "drum", "hunt", "snow", "happy", "hip"],
  ["leaf", "mention", "warm", "useful", "acid", "volume", "stand", "coconut", "together", "rookie", "glove", "fabric"],
  ["word", "entry", "differ", "garment", "maze", "system", "palace", "nice", "level", "domain", "tray", "acid"],
  ["ignore", "cause", "space", "thumb", "siren", "unfair", "wedding", "cruise", "scrub", "emerge", "dial", "asset"],
  ["grab", "elite", "media", "oven", "become", "sick", "ball", "rude", "twin", "unveil", "boat", "blade"],
  ["tumble", "mutual", "enhance", "wrong", "have", "divorce", "luggage", "same", "burger", "scrap", "check", "debris"],
  ["assume", "inspire", "beyond", "habit", "uncle", "axis", "poem", "toss", "cost", "coffee", "draft", "oyster"],
  ["green", "dilemma", "quarter", "refuse", "visit", "front", "exist", "resource", "inform", "chase", "whisper", "cross"],
  ["owner", "spring", "quit", "monkey", "panel", "tent", "tiny", "lumber", "safe", "equal", "cross", "balcony"],
  ["throw", "curve", "feed", "bargain", "cupboard", "sock", "brick", "unique", "drift", "balcony", "liberty", "project"],
  ["coral", "huge", "enrich", "elbow", "load", "host", "autumn", "sense", "mansion", "youth", "quality", "become"],
  ["gold", "seat", "monkey", "mechanic", "tortoise", "glide", "wedding", "gospel", "snake", "execute", "focus", "mixture"],
  ["attack", "casual", "spice", "unveil", "real", "aspect", "arch", "shadow", "agent", "salad", "book", "chaos"],
  ["walnut", "tilt", "major", "unable", "census", "income", "owner", "toward", "later", "funny", "twice", "fun"],
  ["side", "always", "grit", "unknown", "ginger", "robust", "diamond", "wall", "weasel", "will", "exit", "tomorrow"],
  ["work", "couch", "true", "logic", "protect", "state", "begin", "purity", "copper", "purpose", "label", "label"],
  ["wolf", "merry", "ceiling", "figure", "come", "shrug", "toe", "spread", "student", "cigar", "lamp", "gym"],
  ["scheme", "auto", "music", "address", "mosquito", "output", "boost", "defy", "punch", "fall", "tool", "prison"],
  ["various", "estate", "rose", "lady", "dignity", "follow", "story", "tiny", "pull", "warrior", "toss", "case"],
  ["captain", "trash", "flip", "club", "cry", "owner", "prosper", "blanket", "country", "ivory", "embrace", "casual"],
  ["grace", "dilemma", "antique", "robot", "dish", "genre", "fortune", "inhale", "diamond", "must", "release", "insect"],
  ["ancient", "predict", "effort", "stadium", "perfect", "lounge", "know", "yard", "slice", "civil", "era", "bargain"],
  ["alpha", "nice", "dinner", "social", "juice", "search", "ugly", "review", "strategy", "later", "ripple", "fragile"],
  ["claw", "air", "barely", "gun", "scale", "interest", "dash", "dignity", "library", "double", "bright", "long"],
  ["fatigue", "vapor", "acquire", "merit", "oval", "bind", "wealth", "warfare", "pencil", "dose", "size", "climb"],
  ["since", "force", "network", "bleak", "tiny", "wide", "habit", "unaware", "royal", "exile", "cricket", "direct"],
  ["patch", "consider", "eight", "defense", "salad", "save", "food", "concert", "olympic", "like", "zebra", "odor"],
  ["more", "daring", "flip", "lock", "mind", "tray", "naive", "address", "medal", "rent", "mountain", "chaos"],
  ["cargo", "rebuild", "universe", "category", "black", "divorce", "upper", "picnic", "logic", "boring", "atom", "slow"],
  ["grace", "coil", "stock", "glance", "must", "bullet", "tooth", "laundry", "more", "asthma", "neutral", "grit"],
  ["trouble", "enter", "climb", "motion", "disorder", "rack", "crack", "ensure", "autumn", "delay", "enroll", "cotton"],
  ["throw", "wedding", "exclude", "dwarf", "gauge", "pigeon", "bulb", "gift", "pull", "fancy", "duty", "welcome"],
  ["dad", "sheriff", "surround", "jungle", "high", "pet", "radar", "wage", "another", "kick", "oak", "donkey"],
  ["mixture", "time", "debate", "runway", "never", "grape", "vicious", "client", "now", "first", "video", "wait"],
  ["day", "twice", "wise", "tape", "pledge", "travel", "dose", "artefact", "author", "humor", "topple", "always"],
  ["clock", "clutch", "deal", "garbage", "stadium", "develop", "soldier", "escape", "dance", "parade", "educate", "hurdle"],
  ["canal", "screen", "power", "thunder", "emerge", "meat", "injury", "wasp", "large", "cabbage", "giraffe", "view"],
  ["donor", "obscure", "pattern", "crowd", "script", "sweet", "evil", "try", "detect", "permit", "tunnel", "crew"],
  ["raise", "scout", "gate", "cancel", "phone", "pottery", "decline", "beef", "fitness", "orbit", "bulk", "popular"],
  ["miracle", "debris", "salad", "chalk", "punch", "pill", "debate", "walnut", "rival", "person", "strike", "escape"],
  ["neglect", "vacuum", "charge", "glide", "people", "view", "sun", "program", "space", "fence", "sustain", "avoid"],
  ["vehicle", "scene", "room", "steak", "social", "auction", "stage", "midnight", "guitar", "artist", "dumb", "wall"],
  ["anger", "dentist", "canal", "sheriff", "travel", "mom", "meadow", "laugh", "all", "autumn", "rug", "worry"],
  ["blame", "horse", "genuine", "fantasy", "feature", "enrich", "stick", "razor", "present", "ordinary", "raw", "truth"],
  ["behave", "speed", "exile", "antenna", "lady", "link", "enough", "solid", "travel", "always", "six", "waste"],
  ["almost", "tree", "banana", "million", "critic", "trash", "weather", "clap", "memory", "strike", "delay", "random"],
  ["goose", "number", "trash", "empty", "rude", "sponsor", "essence", "lock", "wrong", "soccer", "episode", "ceiling"],
  ["slab", "file", "noodle", "hollow", "pelican", "clever", "work", "census", "day", "diet", "advance", "token"],
  ["light", "umbrella", "whip", "slot", "panther", "puppy", "basket", "wise", "patient", "tuna", "phone", "clever"],
  ["addict", "sword", "major", "nation", "inject", "oak", "worth", "shine", "sheriff", "dignity", "story", "pizza"],
  ["sheriff", "prepare", "mimic", "grant", "present", "sad", "knife", "region", "clinic", "phrase", "clock", "access"],
  ["embody", "rug", "kite", "frequent", "law", "impact", "deer", "warfare", "panic", "bottom", "merge", "sustain"],
  ["three", "easy", "abuse", "brisk", "beauty", "junk", "kiwi", "detail", "vehicle", "example", "vague", "reflect"],
  ["defense", "lift", "heavy", "mix", "embrace", "hollow", "east", "gloom", "invest", "omit", "inspire", "uphold"],
  ["hurdle", "border", "also", "idea", "offer", "shield", "whip", "field", "journey", "purchase", "series", "limit"],
  ["mother", "crane", "rotate", "drink", "surface", "grow", "rate", "try", "island", "bonus", "crazy", "shy"],
  ["rich", "route", "entire", "roast", "ketchup", "trip", "wing", "adjust", "asset", "plunge", "attitude", "stadium"],
  ["dragon", "onion", "install", "annual", "harsh", "knee", "moral", "dish", "husband", "orient", "claim", "bike"],
  ["vacuum", "mom", "view", "fabric", "jar", "vote", "wife", "sheriff", "device", "exclude", "security", "girl"],
  ["flee", "genius", "chapter", "sibling", "beauty", "empower", "duck", "utility", "nest", "purchase", "patient", "board"],
  ["utility", "tribe", "shed", "pumpkin", "vapor", "blush", "provide", "banana", "public", "library", "rug", "express"],
  ["merit", "journey", "cycle", "panda", "that", "clerk", "history", "obscure", "slot", "idea", "embody", "solar"],
  ["doctor", "catch", "bunker", "voice", "pattern", "only", "planet", "range", "flock", "either", "stairs", "tuition"],
  ["thing", "start", "item", "dice", "glory", "sibling", "account", "prefer", "flip", "relax", "pioneer", "shallow"],
  ["admit", "cement", "immune", "young", "seminar", "radio", "upgrade", "enough", "april", "side", "exit", "sure"],
  ["pole", "actress", "pink", "panda", "dial", "moment", "language", "letter", "test", "awesome", "become", "donkey"],
  ["sunny", "drip", "risk", "town", "salt", "over", "virtual", "loop", "crazy", "spike", "addict", "sword"],
  ["develop", "burger", "recall", "find", "combine", "unit", "pen", "book", "trap", "across", "behind", "mom"],
  ["dove", "frog", "wool", "illness", "grit", "twice", "couch", "avocado", "virtual", "dolphin", "valve", "spider"],
  ["tuna", "only", "march", "magic", "high", "twice", "flavor", "borrow", "hurt", "bullet", "awkward", "similar"],
  ["man", "virus", "differ", "tooth", "change", "smile", "scorpion", "online", "kidney", "turtle", "sauce", "brown"],
  ["later", "cruise", "round", "mail", "tuna", "tribe", "people", "normal", "good", "neck", "tribe", "boost"],
  ["green", "auto", "harvest", "congress", "opera", "advice", "trend", "bid", "favorite", "cluster", "family", "cat"],
  ["labor", "prevent", "economy", "frozen", "wrist", "grass", "scheme", "woman", "solid", "fragile", "pause", "chef"],
  ["blur", "artefact", "various", "proud", "pistol", "nest", "elevator", "disorder", "walnut", "hover", "remember", "account"],
  ["airport", "maple", "leader", "floor", "office", "client", "brass", "abstract", "crater", "leopard", "option", "dad"],
  ["jar", "any", "milk", "endorse", "decorate", "abuse", "develop", "pipe", "kid", "appear", "arrow", "snack"],
  ["culture", "bleak", "play", "retire", "oil", "pause", "upper", "glide", "faculty", "venture", "sauce", "upgrade"],
  ["fetch", "health", "craft", "nominee", "swarm", "cliff", "payment", "ramp", "roast", "adapt", "monkey", "penalty"],
];
export const testStorageKeys = {
  BALANCE_MNEMONICS_INDEX: 'balance-mnemonics-index',
}
