export const addressInstructionsWrapper: string;
export const completionContentWrapper: string;
export const copyIcon: string;
export const copyIconBig: string;
export const infoBox: string;
export const infoBoxLabel: string;
export const link: string;
export const linkInstructionsWrapper: string;
export const qrCode: string;
