export const error: string;
export const instructionsContentWrapper: string;
export const instructionsList: string;
export const instructionsListLabel: string;
export const link: string;
export const printingInstructions: string;
export const submitButtonSpinning: string;
export const subtitle: string;
export const subtitle2: string;
