name: cardano-launcher Windows Tests

on: [push]

jobs:
  tests:
    runs-on: windows-2016
    name: Run tests on Windows
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Fetch deps
        shell: powershell
        run: |
          $url = "https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-jormungandr-win64/latest/download/1"
          $output = "cardano-wallet-jormungandr-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - run: npm install
      - run: npm test
