// @flow
// Cryptographic constants go here
export const WALLET_RECOVERY_PHRASE_WORD_COUNT = 12;
export const ADA_REDEMPTION_PASSPHRASE_LENGHT = 9;
export const ADA_CERTIFICATE_MNEMONIC_LENGHT = 18;
export const PAPER_WALLET_RECOVERY_PHRASE_WORD_COUNT = 27;
export const PAPER_WALLET_PRINTED_WORDS_COUNT = 18;
export const PAPER_WALLET_WRITTEN_WORDS_COUNT = 9;
