'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.YOROI_WALLET_RECOVERY_PHRASE_WORD_COUNT = exports.PAPER_WALLET_WRITTEN_WORDS_COUNT = exports.PAPER_WALLET_PRINTED_WORDS_COUNT = exports.PAPER_WALLET_RECOVERY_PHRASE_WORD_COUNT = exports.ADA_CERTIFICATE_MNEMONIC_LENGTH = exports.WALLET_RECOVERY_PHRASE_WORD_COUNT = exports.ITN_WALLET_RECOVERY_PHRASE_WORD_COUNT = exports.LEGACY_WALLET_RECOVERY_PHRASE_WORD_COUNT = exports.RECOVERY_PHRASE_VERIFICATION_WORD_COUNT = void 0;
// Cryptographic constants go here
exports.RECOVERY_PHRASE_VERIFICATION_WORD_COUNT = [12, 15, 18, 24];
exports.LEGACY_WALLET_RECOVERY_PHRASE_WORD_COUNT = 12;
exports.ITN_WALLET_RECOVERY_PHRASE_WORD_COUNT = 15;
exports.WALLET_RECOVERY_PHRASE_WORD_COUNT = 24;
exports.ADA_CERTIFICATE_MNEMONIC_LENGTH = 18;
exports.PAPER_WALLET_RECOVERY_PHRASE_WORD_COUNT = 27;
exports.PAPER_WALLET_PRINTED_WORDS_COUNT = 18;
exports.PAPER_WALLET_WRITTEN_WORDS_COUNT = 9;
exports.YOROI_WALLET_RECOVERY_PHRASE_WORD_COUNT = 15;
//# sourceMappingURL=cryptoConfig.js.map
