// Cryptographic constants go here
export const RECOVERY_PHRASE_VERIFICATION_WORD_COUNT = [12, 15, 18, 24];
export const LEGACY_WALLET_RECOVERY_PHRASE_WORD_COUNT = 12;
export const ITN_WALLET_RECOVERY_PHRASE_WORD_COUNT = 15;
export const WALLET_RECOVERY_PHRASE_WORD_COUNT = 24;
export const ADA_CERTIFICATE_MNEMONIC_LENGTH = 18;
export const PAPER_WALLET_RECOVERY_PHRASE_WORD_COUNT = 27;
export const PAPER_WALLET_PRINTED_WORDS_COUNT = 18;
export const PAPER_WALLET_WRITTEN_WORDS_COUNT = 9;
export const YOROI_WALLET_RECOVERY_PHRASE_WORD_COUNT = 15;
