'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.VOTING_REWARD = exports.VOTING_PHASE_CHECK_INTERVAL = exports.VOTING_REGISTRATION_TRANSACTION_POLLING_INTERVAL = exports.VOTING_REGISTRATION_MIN_TRANSACTION_CONFIRMATIONS = exports.VOTING_REGISTRATION_PIN_CODE_LENGTH = exports.VOTING_REGISTRATION_FEE_CALCULATION_AMOUNT = exports.VOTING_REGISTRATION_MIN_WALLET_FUNDS = void 0;
const { isDev } = global.environment;
exports.VOTING_REGISTRATION_MIN_WALLET_FUNDS = 500; // 500 ADA | unit: ADA
exports.VOTING_REGISTRATION_FEE_CALCULATION_AMOUNT = 1; // 1 ADA | unit: ADA
exports.VOTING_REGISTRATION_PIN_CODE_LENGTH = 4;
exports.VOTING_REGISTRATION_MIN_TRANSACTION_CONFIRMATIONS = isDev ? 2 : 10;
exports.VOTING_REGISTRATION_TRANSACTION_POLLING_INTERVAL = 1000; // 1 second | unit: milliseconds
exports.VOTING_PHASE_CHECK_INTERVAL = 60000; // 60 seconds | unit: milliseconds
exports.VOTING_REWARD = 1040000; // 1,040,000 USD | Unit: dollar
//# sourceMappingURL=votingConfig.js.map
