import {
  WALLET_RECOVERY_PHRASE_WORD_COUNT,
  PAPER_WALLET_RECOVERY_PHRASE_WORD_COUNT,
  LEGACY_WALLET_RECOVERY_PHRASE_WORD_COUNT,
} from './cryptoConfig';

export const CREATE_WALLET_STEPS = [
  'instructions',
  'template',
  'mnemonics',
  'validate',
  'hashImage',
  'config',
];

// WALLET RECOVERY PHRASE CHECKING
export const RECOVERY_PHRASE_VERIFICATION_WARNING = 183; // days
export const RECOVERY_PHRASE_VERIFICATION_NOTIFICATION = 365; // days

export const WALLET_RESTORE_TYPES = {
  REGULAR: 'regular', // Shelley wallet
  CERTIFICATE: 'certificate', // Paper wallet
  LEGACY: 'legacy', // Byron wallet
};

export const RECOVERY_PHRASE_WORD_COUNT_OPTIONS = {
  [WALLET_RESTORE_TYPES.REGULAR]: WALLET_RECOVERY_PHRASE_WORD_COUNT,
  [WALLET_RESTORE_TYPES.CERTIFICATE]: PAPER_WALLET_RECOVERY_PHRASE_WORD_COUNT,
  [WALLET_RESTORE_TYPES.LEGACY]: LEGACY_WALLET_RECOVERY_PHRASE_WORD_COUNT,
};
