// @flow
import { computed } from 'mobx';
import Store from './lib/Store';
import { ROUTES } from '../routes-config';

type StakePool = {
  rank: number,
  id: string,
  name: string,
  description: string,
  url: string,
  controlledStake: number,
  profitMargin: number,
  retiring?: string,
};

export default class StakingStore extends Store {
  showCountdown: boolean = false;
  startDateTime: string = '20191201T000000Z';

  // =================== PUBLIC API ==================== //

  // GETTERS

  @computed get currentRoute(): string {
    return this.stores.router.location.pathname;
  }

  @computed get isStakingPage(): boolean {
    return this.currentRoute.indexOf(ROUTES.STAKING.ROOT) > -1;
  }

  @computed get stakePools(): Array<StakePool> {
    // return this.stakePoolsRequest.result ? this.stakePoolsRequest.result : [];
    return DUMMY_STAKE_POOLS;
  }

  @computed get delegatingStakePools(): Array<StakePool> {
    // return this.stakePoolsRequest.result ? this.stakePoolsRequest.result : [];
    return DUMMY_DELEGATING_STAKE_POOLS;
  }
}

const DUMMY_DELEGATING_STAKE_POOLS = [
  {
    rank: 1,
    id: 'MAUR',
    name: 'Sonair',
    description:
      'Supplement Stomach with Nonautologous Tissue Substitute, Open Approach',
    url: 'https://reuters.com',
    controlledStake: 76,
    profitMargin: 78,
  },
  {
    rank: 3,
    id: 'URNA',
    name: 'Ventosanzap',
    description:
      'Dilation of Middle Colic Artery with Two Intraluminal Devices, Open Approach',
    url: 'https://hhs.gov',
    controlledStake: 49,
    profitMargin: 83,
  },
  {
    rank: 5,
    id: 'INXX',
    name: 'Home Ing',
    description:
      'Bypass Left External Iliac Artery to Left External Iliac Artery with Autologous Arterial Tissue, Open Approach',
    url: 'http://hud.gov',
    controlledStake: 7,
    profitMargin: 27,
  },
  {
    rank: 9,
    id: 'UTXX',
    name: 'Treeflex',
    description: 'Heart and Great Vessels, Supplement',
    url: 'https://amazon.de',
    controlledStake: 18,
    profitMargin: 7,
  },
  {
    rank: 11,
    id: 'NUNC',
    name: 'Viva',
    description:
      'Supplement Left Common Carotid Artery with Nonautologous Tissue Substitute, Percutaneous Approach',
    url: 'https://csmonitor.com',
    controlledStake: 74,
    profitMargin: 19,
  },
  {
    rank: 24,
    id: 'NUNC',
    name: 'Lotstring',
    description:
      'Bypass Bilateral Vas Deferens to Left Vas Deferens, Open Approach',
    url: 'https://who.int',
    controlledStake: 20,
    profitMargin: 76,
    retiring: '2019-12-30T20:19:05Z',
  },
  {
    rank: 153,
    id: 'NUNC',
    name: 'Zathin',
    description:
      'Replacement of Left Internal Iliac Artery with Autologous Tissue Substitute, Open Approach',
    url: 'https://ow.ly',
    controlledStake: 92,
    profitMargin: 69,
  },
  {
    rank: 171,
    id: 'PURU',
    name: 'Cardguard',
    description:
      'Removal of Infusion Device from Uterus and Cervix, Via Natural or Artificial Opening Endoscopic',
    url: 'https://ucla.edu',
    controlledStake: 63,
    profitMargin: 23,
    retiring: '2019-09-24T19:07:59Z',
  },
];

const DUMMY_STAKE_POOLS = [
  {
    rank: 1,
    id: 'MAUR',
    name: 'Sonair',
    description:
      'Supplement Stomach with Nonautologous Tissue Substitute, Open Approach',
    url: 'https://reuters.com',
    controlledStake: 76,
    profitMargin: 78,
  },
  {
    rank: 2,
    id: 'NECX',
    name: 'Bitchip',
    description: 'Dilation of Left Hepatic Duct, Percutaneous Approach',
    url: 'https://tinypic.com',
    controlledStake: 89,
    profitMargin: 63,
  },
  {
    rank: 3,
    id: 'URNA',
    name: 'Ventosanzap',
    description:
      'Dilation of Middle Colic Artery with Two Intraluminal Devices, Open Approach',
    url: 'https://hhs.gov',
    controlledStake: 49,
    profitMargin: 83,
  },
  {
    rank: 4,
    id: 'IDXX',
    name: 'Bytecard',
    description: 'Reposition Left Sphenoid Bone, Open Approach',
    url: 'https://loc.gov',
    controlledStake: 74,
    profitMargin: 54,
  },
  {
    rank: 5,
    id: 'INXX',
    name: 'Home Ing',
    description:
      'Bypass Left External Iliac Artery to Left External Iliac Artery with Autologous Arterial Tissue, Open Approach',
    url: 'http://hud.gov',
    controlledStake: 7,
    profitMargin: 27,
  },
  {
    rank: 6,
    id: 'LEOX',
    name: 'Greenlam',
    description:
      'Introduction of Destructive Agent into Products of Conception, Via Natural or Artificial Opening',
    url: 'http://wp.com',
    controlledStake: 26,
    profitMargin: 42,
    retiring: '2019-08-05T12:28:16Z',
  },
  {
    rank: 7,
    id: 'MAUR',
    name: 'Fixflex',
    description:
      'Bypass Right Hand Vein to Upper Vein with Autologous Tissue Substitute, Percutaneous Endoscopic Approach',
    url: 'https://stanford.edu',
    controlledStake: 90,
    profitMargin: 80,
  },
  {
    rank: 8,
    id: 'TORT',
    name: 'Job',
    description:
      'Bypass Left Pulmonary Artery from Subclavian with Autologous Venous Tissue, Open Approach',
    url: 'https://si.edu',
    controlledStake: 82,
    profitMargin: 19,
  },
  {
    rank: 9,
    id: 'UTXX',
    name: 'Treeflex',
    description: 'Heart and Great Vessels, Supplement',
    url: 'https://amazon.de',
    controlledStake: 18,
    profitMargin: 7,
  },
  {
    rank: 10,
    id: 'RUTR',
    name: 'Cardguard',
    description:
      'High Dose Rate (HDR) Brachytherapy of Liver using Cesium 137 (Cs-137)',
    url: 'https://wsj.com',
    controlledStake: 24,
    profitMargin: 65,
  },
  {
    rank: 11,
    id: 'NUNC',
    name: 'Viva',
    description:
      'Supplement Left Common Carotid Artery with Nonautologous Tissue Substitute, Percutaneous Approach',
    url: 'https://csmonitor.com',
    controlledStake: 74,
    profitMargin: 19,
  },
  {
    rank: 12,
    id: 'QUIS',
    name: 'Hatity',
    description:
      'Insertion of Infusion Device into Right Internal Jugular Vein, Percutaneous Endoscopic Approach',
    url: 'http://etsy.com',
    controlledStake: 90,
    profitMargin: 11,
  },
  {
    rank: 13,
    id: 'VITA',
    name: 'Prodder',
    description:
      'Revision of Drainage Device in Sacrococcygeal Joint, Open Approach',
    url: 'http://tripadvisor.com',
    controlledStake: 87,
    profitMargin: 3,
  },
  {
    rank: 14,
    id: 'VELX',
    name: 'Span',
    description:
      'Excision of Right Shoulder Bursa and Ligament, Percutaneous Endoscopic Approach',
    url: 'http://virginia.edu',
    controlledStake: 83,
    profitMargin: 35,
  },
  {
    rank: 15,
    id: 'ESTX',
    name: 'Prodder',
    description: 'Ultrasonography of Left Knee',
    url: 'https://npr.org',
    controlledStake: 86,
    profitMargin: 11,
  },
  {
    rank: 16,
    id: 'CONS',
    name: 'Biodex',
    description:
      'Release Left Finger Phalanx, Percutaneous Endoscopic Approach',
    url: 'https://ucoz.ru',
    controlledStake: 48,
    profitMargin: 49,
  },
  {
    rank: 17,
    id: 'PENA',
    name: 'It',
    description: 'Reposition Right Hand Muscle, Open Approach',
    url: 'http://cdbaby.com',
    controlledStake: 82,
    profitMargin: 40,
  },
  {
    rank: 18,
    id: 'PEDE',
    name: 'Treeflex',
    description:
      'Revision of Spacer in Left Finger Phalangeal Joint, External Approach',
    url: 'https://google.co.uk',
    controlledStake: 57,
    profitMargin: 44,
  },
  {
    rank: 19,
    id: 'VELI',
    name: 'Y-Solowarm',
    description:
      'Supplement Left Metacarpophalangeal Joint with Synthetic Substitute, Percutaneous Approach',
    url: 'http://chronoengine.com',
    controlledStake: 91,
    profitMargin: 9,
  },
  {
    rank: 20,
    id: 'AMET',
    name: 'Tres-Zap',
    description:
      'Insertion of Infusion Device into Left Temporomandibular Joint, Open Approach',
    url: 'http://blogger.com',
    controlledStake: 79,
    profitMargin: 59,
  },
  {
    rank: 21,
    id: 'ETIA',
    name: 'Bitchip',
    description: 'Change Splint on Left Lower Arm',
    url: 'http://npr.org',
    controlledStake: 100,
    profitMargin: 10,
  },
  {
    rank: 22,
    id: 'ANTE',
    name: 'Trippledex',
    description:
      'Insertion of Internal Fixation Device into Left Thumb Phalanx, Percutaneous Approach',
    url: 'https://google.ca',
    controlledStake: 17,
    profitMargin: 79,
    retiring: '2019-12-09T02:40:49Z',
  },
  {
    rank: 23,
    id: 'ENIM',
    name: 'Zamit',
    description: 'Respiratory System, Drainage',
    url: 'http://com.com',
    controlledStake: 16,
    profitMargin: 44,
  },
  {
    rank: 24,
    id: 'NUNC',
    name: 'Lotstring',
    description:
      'Bypass Bilateral Vas Deferens to Left Vas Deferens, Open Approach',
    url: 'https://who.int',
    controlledStake: 20,
    profitMargin: 76,
    retiring: '2019-12-30T20:19:05Z',
  },
  {
    rank: 25,
    id: 'CONV',
    name: 'Stronghold',
    description:
      'Supplement Right Trunk Muscle with Synthetic Substitute, Open Approach',
    url: 'https://blog.com',
    controlledStake: 58,
    profitMargin: 31,
  },
  {
    rank: 26,
    id: 'MAUR',
    name: 'Cardguard',
    description:
      'Removal of Synthetic Substitute from Right Tarsal, Open Approach',
    url: 'http://state.tx.us',
    controlledStake: 99,
    profitMargin: 81,
  },
  {
    rank: 27,
    id: 'SEDX',
    name: 'Flexidy',
    description:
      'Supplement Right Brachial Vein with Nonautologous Tissue Substitute, Open Approach',
    url: 'https://mozilla.com',
    controlledStake: 96,
    profitMargin: 87,
  },
  {
    rank: 28,
    id: 'NIBH',
    name: 'Zamit',
    description:
      'Replacement of Upper Vein with Synthetic Substitute, Open Approach',
    url: 'https://europa.eu',
    controlledStake: 14,
    profitMargin: 95,
  },
  {
    rank: 29,
    id: 'CONV',
    name: 'Zaam-Dox',
    description: 'Excision of Left Temporal Bone, Percutaneous Approach',
    url: 'http://creativecommons.org',
    controlledStake: 76,
    profitMargin: 7,
    retiring: '2019-10-12T00:46:46Z',
  },
  {
    rank: 30,
    id: 'DOLO',
    name: 'Bitchip',
    description:
      'Repair Endocrine System in Products of Conception, Percutaneous Endoscopic Approach',
    url: 'https://tripod.com',
    controlledStake: 75,
    profitMargin: 99,
  },
  {
    rank: 31,
    id: 'VIVA',
    name: 'Fintone',
    description: 'Monitoring of Venous Pressure, Portal, Percutaneous Approach',
    url: 'https://merriam-webster.com',
    controlledStake: 32,
    profitMargin: 35,
  },
  {
    rank: 32,
    id: 'SEMP',
    name: 'Namfix',
    description:
      'Excision of Left Hypogastric Vein, Percutaneous Endoscopic Approach',
    url: 'https://craigslist.org',
    controlledStake: 99,
    profitMargin: 4,
  },
  {
    rank: 33,
    id: 'AXX',
    name: 'Fintone',
    description:
      'Extraction of Thoracic Sympathetic Nerve, Percutaneous Endoscopic Approach',
    url: 'http://amazon.co.uk',
    controlledStake: 21,
    profitMargin: 49,
    retiring: '2019-12-15T08:44:34Z',
  },
  {
    rank: 34,
    id: 'UTXX',
    name: 'Span',
    description:
      'Replacement of Right Colic Artery with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    url: 'http://kickstarter.com',
    controlledStake: 9,
    profitMargin: 15,
  },
  {
    rank: 35,
    id: 'ETXX',
    name: 'Treeflex',
    description:
      'Extirpation of Matter from Cervix, Percutaneous Endoscopic Approach',
    url: 'http://mashable.com',
    controlledStake: 11,
    profitMargin: 54,
  },
  {
    rank: 36,
    id: 'VELX',
    name: 'Cardguard',
    description: 'Drainage of Head Muscle, Open Approach',
    url: 'http://biblegateway.com',
    controlledStake: 43,
    profitMargin: 30,
  },
  {
    rank: 37,
    id: 'JUST',
    name: 'Viva',
    description: 'Hyperthermia of Mediastinum',
    url: 'https://storify.com',
    controlledStake: 68,
    profitMargin: 99,
  },
  {
    rank: 38,
    id: 'POTE',
    name: 'Hatity',
    description: 'Transfer Accessory Nerve to Facial Nerve, Open Approach',
    url: 'https://fotki.com',
    controlledStake: 79,
    profitMargin: 26,
  },
  {
    rank: 39,
    id: 'NEQU',
    name: 'Stringtough',
    description: 'Extraction of Lower Vein, Percutaneous Approach',
    url: 'http://columbia.edu',
    controlledStake: 94,
    profitMargin: 45,
  },
  {
    rank: 40,
    id: 'FUSC',
    name: 'Greenlam',
    description: 'Repair Left Vertebral Vein, Percutaneous Endoscopic Approach',
    url: 'http://qq.com',
    controlledStake: 49,
    profitMargin: 60,
  },
  {
    rank: 41,
    id: 'CONS',
    name: 'Sonair',
    description:
      'Bypass Left Popliteal Artery to Popliteal Artery with Autologous Arterial Tissue, Percutaneous Endoscopic Approach',
    url: 'https://wufoo.com',
    controlledStake: 4,
    profitMargin: 69,
  },
  {
    rank: 42,
    id: 'ODIO',
    name: 'Aerified',
    description:
      'Bypass Left Atrium to Pulmonary Vein Confluence with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    url: 'https://japanpost.jp',
    controlledStake: 78,
    profitMargin: 95,
  },
  {
    rank: 43,
    id: 'NONX',
    name: 'Voltsillam',
    description: 'Fragmentation in Ampulla of Vater, External Approach',
    url: 'http://squarespace.com',
    controlledStake: 25,
    profitMargin: 50,
  },
  {
    rank: 44,
    id: 'MAEC',
    name: 'Voyatouch',
    description:
      'Computerized Tomography (CT Scan) of Multiple Coronary Artery Bypass Grafts',
    url: 'https://buzzfeed.com',
    controlledStake: 59,
    profitMargin: 34,
  },
  {
    rank: 45,
    id: 'NAMX',
    name: 'Holdlamis',
    description:
      'Supplement Right Lacrimal Bone with Synthetic Substitute, Open Approach',
    url: 'http://xrea.com',
    controlledStake: 70,
    profitMargin: 85,
    retiring: '2019-11-18T11:32:25Z',
  },
  {
    rank: 46,
    id: 'NONX',
    name: 'Solarbreeze',
    description:
      'Fusion of Right Elbow Joint with External Fixation Device, Open Approach',
    url: 'https://rediff.com',
    controlledStake: 44,
    profitMargin: 87,
  },
  {
    rank: 47,
    id: 'TORT',
    name: 'Holdlamis',
    description:
      'Revision of Intraluminal Device in Right Ear, External Approach',
    url: 'http://fotki.com',
    controlledStake: 39,
    profitMargin: 89,
  },
  {
    rank: 48,
    id: 'POTE',
    name: 'Subin',
    description: 'Excision of Right Thorax Muscle, Percutaneous Approach',
    url: 'http://deviantart.com',
    controlledStake: 47,
    profitMargin: 5,
  },
  {
    rank: 49,
    id: 'AMET',
    name: 'Redhold',
    description: 'Inspection of Kidney, Percutaneous Endoscopic Approach',
    url: 'https://lycos.com',
    controlledStake: 88,
    profitMargin: 98,
  },
  {
    rank: 50,
    id: 'NAMX',
    name: 'Konklab',
    description:
      'Dilation of Hepatic Artery with Intraluminal Device, Open Approach',
    url: 'http://ocn.ne.jp',
    controlledStake: 24,
    profitMargin: 86,
  },
  {
    rank: 51,
    id: 'PEDE',
    name: 'Bitchip',
    description:
      'Excision of Left Trunk Tendon, Percutaneous Endoscopic Approach',
    url: 'http://geocities.com',
    controlledStake: 27,
    profitMargin: 94,
  },
  {
    rank: 52,
    id: 'UTXX',
    name: 'Konklab',
    description:
      'Extraction of Right Frontal Sinus, Percutaneous Endoscopic Approach',
    url: 'https://hhs.gov',
    controlledStake: 6,
    profitMargin: 61,
    retiring: '2019-06-23T11:38:25Z',
  },
  {
    rank: 53,
    id: 'LORE',
    name: 'Stringtough',
    description:
      'Supplement Celiac Artery with Synthetic Substitute, Percutaneous Endoscopic Approach',
    url: 'https://businesswire.com',
    controlledStake: 51,
    profitMargin: 43,
  },
  {
    rank: 54,
    id: 'HACX',
    name: 'Alpha',
    description:
      'Excision of Pituitary Gland, Percutaneous Approach, Diagnostic',
    url: 'https://about.me',
    controlledStake: 39,
    profitMargin: 58,
    retiring: '2019-06-20T03:47:49Z',
  },
  {
    rank: 55,
    id: 'LECT',
    name: 'Ronstring',
    description: 'Inspection of Spinal Cord, Percutaneous Endoscopic Approach',
    url: 'http://seattletimes.com',
    controlledStake: 15,
    profitMargin: 57,
  },
  {
    rank: 56,
    id: 'MAGN',
    name: 'Holdlamis',
    description:
      'Insertion of Spacer into Right Carpal Joint, Percutaneous Approach',
    url: 'https://icq.com',
    controlledStake: 36,
    profitMargin: 74,
  },
  {
    rank: 57,
    id: 'MAEC',
    name: 'Domainer',
    description:
      'Introduction of Other Antineoplastic into Upper GI, Via Natural or Artificial Opening Endoscopic',
    url: 'https://omniture.com',
    controlledStake: 76,
    profitMargin: 73,
  },
  {
    rank: 58,
    id: 'CRAS',
    name: 'Biodex',
    description:
      'Dilation of Hepatic Artery with Three Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach',
    url: 'https://ow.ly',
    controlledStake: 30,
    profitMargin: 62,
  },
  {
    rank: 59,
    id: 'ANTE',
    name: 'Holdlamis',
    description:
      'Occlusion of Right Colic Artery with Extraluminal Device, Open Approach',
    url: 'http://behance.net',
    controlledStake: 27,
    profitMargin: 57,
  },
  {
    rank: 60,
    id: 'VARI',
    name: 'Trippledex',
    description:
      'Supplement Right Peroneal Artery with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    url: 'http://live.com',
    controlledStake: 14,
    profitMargin: 13,
  },
  {
    rank: 61,
    id: 'INXX',
    name: 'Bitwolf',
    description:
      'Revision of Synthetic Substitute in Pelvic Cavity, External Approach',
    url: 'http://behance.net',
    controlledStake: 32,
    profitMargin: 68,
  },
  {
    rank: 62,
    id: 'LOBO',
    name: 'Cardify',
    description: 'Repair Right Eustachian Tube, External Approach',
    url: 'https://cnbc.com',
    controlledStake: 62,
    profitMargin: 16,
  },
  {
    rank: 63,
    id: 'SEMP',
    name: 'Regrant',
    description: 'Repair Hemiazygos Vein, Percutaneous Approach',
    url: 'http://huffingtonpost.com',
    controlledStake: 61,
    profitMargin: 48,
    retiring: '2019-05-24T03:19:22Z',
  },
  {
    rank: 64,
    id: 'QUIS',
    name: 'Stronghold',
    description:
      'Plain Radiography of Left Hand/Finger Joint using High Osmolar Contrast',
    url: 'https://nba.com',
    controlledStake: 9,
    profitMargin: 91,
    retiring: '2019-08-19T03:36:13Z',
  },
  {
    rank: 65,
    id: 'JUST',
    name: 'Alpha',
    description: 'Drainage of Right Hand Vein, Open Approach, Diagnostic',
    url: 'http://techcrunch.com',
    controlledStake: 37,
    profitMargin: 43,
  },
  {
    rank: 66,
    id: 'MORB',
    name: 'Cardify',
    description:
      'Bypass Splenic Artery to Bilateral Renal Artery with Autologous Venous Tissue, Open Approach',
    url: 'http://cisco.com',
    controlledStake: 5,
    profitMargin: 2,
  },
  {
    rank: 67,
    id: 'SEDX',
    name: 'Treeflex',
    description:
      'Bypass Right Pulmonary Artery from Carotid with Zooplastic Tissue, Open Approach',
    url: 'http://cbsnews.com',
    controlledStake: 24,
    profitMargin: 67,
  },
  {
    rank: 68,
    id: 'NAMX',
    name: 'Solarbreeze',
    description:
      'Removal of Autologous Tissue Substitute from Right Eye, External Approach',
    url: 'https://mlb.com',
    controlledStake: 47,
    profitMargin: 8,
  },
  {
    rank: 69,
    id: 'NONU',
    name: 'Zathin',
    description: 'Release Right Upper Arm Muscle, External Approach',
    url: 'https://nps.gov',
    controlledStake: 51,
    profitMargin: 100,
  },
  {
    rank: 70,
    id: 'DICT',
    name: 'Voyatouch',
    description:
      'Extirpation of Matter from Duodenum, Percutaneous Endoscopic Approach',
    url: 'https://hc360.com',
    controlledStake: 42,
    profitMargin: 98,
  },
  {
    rank: 71,
    id: 'QUIS',
    name: 'Flowdesk',
    description:
      'Drainage of Large Intestine with Drainage Device, Via Natural or Artificial Opening',
    url: 'http://miitbeian.gov.cn',
    controlledStake: 77,
    profitMargin: 99,
  },
  {
    rank: 72,
    id: 'CURA',
    name: 'Holdlamis',
    description:
      'Low Dose Rate (LDR) Brachytherapy of Left Breast using Cesium 137 (Cs-137)',
    url: 'https://loc.gov',
    controlledStake: 100,
    profitMargin: 84,
  },
  {
    rank: 73,
    id: 'AMET',
    name: 'Span',
    description: 'Mouth and Throat, Resection',
    url: 'https://etsy.com',
    controlledStake: 95,
    profitMargin: 79,
  },
  {
    rank: 74,
    id: 'MAGN',
    name: 'Otcom',
    description:
      'Computerized Tomography (CT Scan) of Pancreas using High Osmolar Contrast, Unenhanced and Enhanced',
    url: 'https://hud.gov',
    controlledStake: 91,
    profitMargin: 58,
  },
  {
    rank: 75,
    id: 'VIVA',
    name: 'Subin',
    description: 'Beam Radiation of Kidney using Photons 1 - 10 MeV',
    url: 'http://rediff.com',
    controlledStake: 52,
    profitMargin: 97,
  },
  {
    rank: 76,
    id: 'RISU',
    name: 'Temp',
    description: 'Drainage of Left Elbow Joint, Open Approach',
    url: 'https://pcworld.com',
    controlledStake: 26,
    profitMargin: 46,
    retiring: '2019-10-27T23:37:09Z',
  },
  {
    rank: 77,
    id: 'ACXX',
    name: 'Trippledex',
    description:
      'Release Left Lower Lung Lobe, Percutaneous Endoscopic Approach',
    url: 'http://techcrunch.com',
    controlledStake: 92,
    profitMargin: 25,
  },
  {
    rank: 78,
    id: 'LIBE',
    name: 'Lotstring',
    description:
      'Revision of Drainage Device in Right Ankle Joint, Percutaneous Approach',
    url: 'https://w3.org',
    controlledStake: 69,
    profitMargin: 55,
  },
  {
    rank: 79,
    id: 'PELL',
    name: 'Konklab',
    description:
      'Removal of Radioactive Element from Pleura, Via Natural or Artificial Opening Endoscopic',
    url: 'https://addtoany.com',
    controlledStake: 95,
    profitMargin: 2,
  },
  {
    rank: 80,
    id: 'VOLU',
    name: 'Y-Solowarm',
    description:
      'Insertion of Infusion Device into Left Lower Extremity, Percutaneous Endoscopic Approach',
    url: 'https://desdev.cn',
    controlledStake: 39,
    profitMargin: 71,
  },
  {
    rank: 81,
    id: 'LUCT',
    name: 'Greenlam',
    description:
      'Dilation of Left Axillary Artery, Bifurcation, with Two Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach',
    url: 'https://t.co',
    controlledStake: 33,
    profitMargin: 92,
  },
  {
    rank: 82,
    id: 'AXX',
    name: 'Veribet',
    description: 'Destruction of Right Scapula, Percutaneous Approach',
    url: 'http://cnet.com',
    controlledStake: 72,
    profitMargin: 78,
  },
  {
    rank: 83,
    id: 'POSU',
    name: 'Trippledex',
    description: 'Reposition Cervical Vertebral Joint, External Approach',
    url: 'https://indiegogo.com',
    controlledStake: 41,
    profitMargin: 62,
  },
  {
    rank: 84,
    id: 'DUIS',
    name: 'Transcof',
    description:
      'Dilation of Trachea with Intraluminal Device, Percutaneous Endoscopic Approach',
    url: 'https://spiegel.de',
    controlledStake: 10,
    profitMargin: 88,
  },
  {
    rank: 85,
    id: 'LACI',
    name: 'Bigtax',
    description:
      'Bypass Left Common Carotid Artery to Left Extracranial Artery with Autologous Arterial Tissue, Open Approach',
    url: 'http://psu.edu',
    controlledStake: 98,
    profitMargin: 51,
    retiring: '2019-06-23T07:56:24Z',
  },
  {
    rank: 86,
    id: 'CURA',
    name: 'Asoka',
    description: 'Excision of Mitral Valve, Percutaneous Approach, Diagnostic',
    url: 'http://com.com',
    controlledStake: 33,
    profitMargin: 85,
  },
  {
    rank: 87,
    id: 'FELI',
    name: 'Alpha',
    description: 'Dilation of Lower Artery, Percutaneous Approach',
    url: 'https://state.gov',
    controlledStake: 65,
    profitMargin: 95,
  },
  {
    rank: 88,
    id: 'TEMP',
    name: 'Span',
    description:
      'Fluoroscopy of Superior Vena Cava using High Osmolar Contrast, Guidance',
    url: 'https://meetup.com',
    controlledStake: 29,
    profitMargin: 28,
  },
  {
    rank: 89,
    id: 'INTE',
    name: 'Regrant',
    description: 'Removal of Cast on Left Toe',
    url: 'http://sina.com.cn',
    controlledStake: 82,
    profitMargin: 14,
  },
  {
    rank: 90,
    id: 'ODIO',
    name: 'Redhold',
    description:
      'Reposition Left Lower Femur with External Fixation Device, Percutaneous Endoscopic Approach',
    url: 'https://noaa.gov',
    controlledStake: 65,
    profitMargin: 11,
    retiring: '2019-09-07T08:14:35Z',
  },
  {
    rank: 91,
    id: 'VIVA',
    name: 'Stim',
    description:
      'Revision of Autologous Tissue Substitute in Left Sacroiliac Joint, Percutaneous Endoscopic Approach',
    url: 'https://icio.us',
    controlledStake: 89,
    profitMargin: 41,
    retiring: '2019-05-30T13:39:56Z',
  },
  {
    rank: 92,
    id: 'METU',
    name: 'Tempsoft',
    description: 'Insertion of Other Device into Neck, Open Approach',
    url: 'http://hubpages.com',
    controlledStake: 57,
    profitMargin: 78,
  },
  {
    rank: 93,
    id: 'JUST',
    name: 'Fixflex',
    description:
      'Extirpation of Matter from Trachea, Via Natural or Artificial Opening Endoscopic',
    url: 'http://php.net',
    controlledStake: 9,
    profitMargin: 88,
  },
  {
    rank: 94,
    id: 'ELIT',
    name: 'Temp',
    description:
      'Excision of Right Lower Leg Subcutaneous Tissue and Fascia, Open Approach',
    url: 'http://accuweather.com',
    controlledStake: 61,
    profitMargin: 75,
  },
  {
    rank: 95,
    id: 'HABI',
    name: 'Subin',
    description:
      'Drainage of Right Knee Tendon with Drainage Device, Open Approach',
    url: 'https://goodreads.com',
    controlledStake: 27,
    profitMargin: 97,
  },
  {
    rank: 96,
    id: 'MOLE',
    name: 'Sub-Ex',
    description:
      'Revision of Internal Fixation Device in Lumbar Vertebral Joint, Open Approach',
    url: 'https://epa.gov',
    controlledStake: 98,
    profitMargin: 95,
    retiring: '2019-06-13T02:08:56Z',
  },
  {
    rank: 97,
    id: 'IPSU',
    name: 'Cardify',
    description:
      'Excision of Right Ankle Bursa and Ligament, Percutaneous Approach, Diagnostic',
    url: 'https://mail.ru',
    controlledStake: 13,
    profitMargin: 46,
  },
  {
    rank: 98,
    id: 'MUSX',
    name: 'Temp',
    description:
      'Extirpation of Matter from Right Femoral Artery, Percutaneous Endoscopic Approach',
    url: 'http://ucsd.edu',
    controlledStake: 44,
    profitMargin: 99,
  },
  {
    rank: 99,
    id: 'VITA',
    name: 'Bamity',
    description:
      'Computerized Tomography (CT Scan) of Prostate using Low Osmolar Contrast, Unenhanced and Enhanced',
    url: 'https://nationalgeographic.com',
    controlledStake: 7,
    profitMargin: 35,
  },
  {
    rank: 100,
    id: 'DUIX',
    name: 'Solarbreeze',
    description:
      'Supplement Left Internal Carotid Artery with Nonautologous Tissue Substitute, Percutaneous Approach',
    url: 'https://goodreads.com',
    controlledStake: 43,
    profitMargin: 81,
  },
  {
    rank: 101,
    id: 'EGET',
    name: 'Trippledex',
    description:
      'Fluoroscopy of Uterus and Fallopian Tubes using Other Contrast',
    url: 'http://msn.com',
    controlledStake: 18,
    profitMargin: 28,
  },
  {
    rank: 102,
    id: 'LIBE',
    name: 'Bitwolf',
    description:
      'Bypass Left Radial Artery to Lower Arm Vein with Autologous Arterial Tissue, Open Approach',
    url: 'http://go.com',
    controlledStake: 41,
    profitMargin: 13,
  },
  {
    rank: 103,
    id: 'PART',
    name: 'Zathin',
    description:
      'Introduction of Oxazolidinones into Central Artery, Percutaneous Approach',
    url: 'https://census.gov',
    controlledStake: 25,
    profitMargin: 87,
  },
  {
    rank: 104,
    id: 'SAPI',
    name: 'Vagram',
    description:
      'Removal of Nonautologous Tissue Substitute from Face, Percutaneous Approach',
    url: 'http://last.fm',
    controlledStake: 28,
    profitMargin: 73,
  },
  {
    rank: 105,
    id: 'UTXX',
    name: 'Overhold',
    description:
      'Occlusion of Left Cephalic Vein, Percutaneous Endoscopic Approach',
    url: 'https://nsw.gov.au',
    controlledStake: 75,
    profitMargin: 10,
  },
  {
    rank: 106,
    id: 'MATT',
    name: 'Latlux',
    description: 'Drainage of Right Trunk Tendon, Open Approach',
    url: 'http://jigsy.com',
    controlledStake: 2,
    profitMargin: 77,
  },
  {
    rank: 107,
    id: 'PEDE',
    name: 'Subin',
    description:
      'Excision of Right Vocal Cord, Via Natural or Artificial Opening, Diagnostic',
    url: 'https://friendfeed.com',
    controlledStake: 86,
    profitMargin: 94,
  },
  {
    rank: 108,
    id: 'AMET',
    name: 'Asoka',
    description: 'Dilation of Left Lacrimal Duct, Open Approach',
    url: 'http://amazon.de',
    controlledStake: 48,
    profitMargin: 49,
  },
  {
    rank: 109,
    id: 'LIGU',
    name: 'Bigtax',
    description:
      'Supplement Lumbar Vertebra with Nonautologous Tissue Substitute, Percutaneous Approach',
    url: 'http://boston.com',
    controlledStake: 24,
    profitMargin: 15,
  },
  {
    rank: 110,
    id: 'PRET',
    name: 'Zamit',
    description: 'Release Right Middle Lobe Bronchus, Percutaneous Approach',
    url: 'http://ihg.com',
    controlledStake: 46,
    profitMargin: 8,
  },
  {
    rank: 111,
    id: 'VELX',
    name: 'Home Ing',
    description:
      'Bypass Coronary Artery, Four or More Arteries from Right Internal Mammary with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
    url: 'https://usatoday.com',
    controlledStake: 61,
    profitMargin: 76,
  },
  {
    rank: 112,
    id: 'ERAT',
    name: 'Voyatouch',
    description:
      'Bypass Abdominal Aorta to Celiac Artery with Autologous Arterial Tissue, Open Approach',
    url: 'http://senate.gov',
    controlledStake: 29,
    profitMargin: 61,
  },
  {
    rank: 113,
    id: 'SCEL',
    name: 'Zamit',
    description: 'Computerized Tomography (CT Scan) of Right Wrist',
    url: 'https://yahoo.com',
    controlledStake: 73,
    profitMargin: 35,
  },
  {
    rank: 114,
    id: 'LEOX',
    name: 'Redhold',
    description:
      'Supplement Stomach with Autologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic',
    url: 'http://webeden.co.uk',
    controlledStake: 13,
    profitMargin: 29,
  },
  {
    rank: 115,
    id: 'BLAN',
    name: 'Sonair',
    description:
      'Insertion of Infusion Device into Scrotum and Tunica Vaginalis, Via Natural or Artificial Opening',
    url: 'https://netscape.com',
    controlledStake: 91,
    profitMargin: 89,
    retiring: '2019-11-17T22:08:57Z',
  },
  {
    rank: 116,
    id: 'MATT',
    name: 'Tampflex',
    description: 'Inspection of Lower Artery, Percutaneous Endoscopic Approach',
    url: 'http://example.com',
    controlledStake: 45,
    profitMargin: 23,
  },
  {
    rank: 117,
    id: 'SEMX',
    name: 'Zontrax',
    description:
      'Removal of Nonautologous Tissue Substitute from Lower Extremity Subcutaneous Tissue and Fascia, Open Approach',
    url: 'https://buzzfeed.com',
    controlledStake: 11,
    profitMargin: 41,
  },
  {
    rank: 118,
    id: 'NEQU',
    name: 'Regrant',
    description:
      'Occlusion of Thorax Lymphatic with Extraluminal Device, Percutaneous Endoscopic Approach',
    url: 'https://hibu.com',
    controlledStake: 37,
    profitMargin: 6,
  },
  {
    rank: 119,
    id: 'LACI',
    name: 'Fix San',
    description:
      'Reposition Right Metacarpocarpal Joint with Internal Fixation Device, Open Approach',
    url: 'http://bandcamp.com',
    controlledStake: 88,
    profitMargin: 27,
  },
  {
    rank: 120,
    id: 'LUCT',
    name: 'Bitwolf',
    description: 'Reposition Left Acetabulum, Open Approach',
    url: 'http://nba.com',
    controlledStake: 92,
    profitMargin: 75,
  },
  {
    rank: 121,
    id: 'RHON',
    name: 'Bamity',
    description: 'Bypass Jejunum to Cutaneous, Open Approach',
    url: 'http://mozilla.org',
    controlledStake: 28,
    profitMargin: 32,
  },
  {
    rank: 122,
    id: 'QUIS',
    name: 'Home Ing',
    description:
      'Bypass Ascending Colon to Rectum with Nonautologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic',
    url: 'http://yellowbook.com',
    controlledStake: 79,
    profitMargin: 44,
    retiring: '2019-12-26T07:43:52Z',
  },
  {
    rank: 123,
    id: 'BLAN',
    name: 'Bigtax',
    description:
      'Fusion of Right Knee Joint with Nonautologous Tissue Substitute, Open Approach',
    url: 'https://blogger.com',
    controlledStake: 79,
    profitMargin: 1,
  },
  {
    rank: 124,
    id: 'ULTR',
    name: 'Toughjoyfax',
    description:
      'Plain Radiography of Portal and Splanchnic Veins using Low Osmolar Contrast',
    url: 'https://reddit.com',
    controlledStake: 39,
    profitMargin: 63,
  },
  {
    rank: 125,
    id: 'ALIQ',
    name: 'Zoolab',
    description:
      'Revision of Synthetic Substitute in Diaphragm, Via Natural or Artificial Opening',
    url: 'http://flickr.com',
    controlledStake: 75,
    profitMargin: 31,
  },
  {
    rank: 126,
    id: 'TURP',
    name: 'Daltfresh',
    description:
      'Drainage of Common Bile Duct, Percutaneous Endoscopic Approach',
    url: 'https://prnewswire.com',
    controlledStake: 62,
    profitMargin: 11,
    retiring: '2019-06-27T06:07:03Z',
  },
  {
    rank: 127,
    id: 'SEDX',
    name: 'Wrapsafe',
    description:
      'Drainage of Left Ankle Region, Percutaneous Approach, Diagnostic',
    url: 'http://virginia.edu',
    controlledStake: 4,
    profitMargin: 55,
  },
  {
    rank: 128,
    id: 'SITX',
    name: 'Overhold',
    description:
      'Replacement of Left Scapula with Nonautologous Tissue Substitute, Open Approach',
    url: 'http://yellowbook.com',
    controlledStake: 27,
    profitMargin: 45,
    retiring: '2019-10-01T15:43:07Z',
  },
  {
    rank: 129,
    id: 'ULTR',
    name: 'Trippledex',
    description: 'Destruction of Bilateral Lungs, Percutaneous Approach',
    url: 'http://so-net.ne.jp',
    controlledStake: 32,
    profitMargin: 86,
    retiring: '2019-07-07T12:41:17Z',
  },
  {
    rank: 130,
    id: 'CONS',
    name: 'Stim',
    description: 'Drainage of Accessory Nerve, Open Approach, Diagnostic',
    url: 'https://earthlink.net',
    controlledStake: 33,
    profitMargin: 29,
    retiring: '2019-09-10T08:10:31Z',
  },
  {
    rank: 131,
    id: 'SAPI',
    name: 'Sonair',
    description: 'Release Brain, Percutaneous Endoscopic Approach',
    url: 'http://wikia.com',
    controlledStake: 46,
    profitMargin: 80,
  },
  {
    rank: 132,
    id: 'SAPI',
    name: 'Redhold',
    description: 'Repair Upper Artery, Percutaneous Endoscopic Approach',
    url: 'https://cpanel.net',
    controlledStake: 98,
    profitMargin: 51,
  },
  {
    rank: 133,
    id: 'SEMP',
    name: 'Andalax',
    description:
      'Computerized Tomography (CT Scan) of Abdomen using High Osmolar Contrast, Unenhanced and Enhanced',
    url: 'http://soundcloud.com',
    controlledStake: 61,
    profitMargin: 43,
  },
  {
    rank: 134,
    id: 'SEMX',
    name: 'Ronstring',
    description: 'Family Psychotherapy',
    url: 'http://go.com',
    controlledStake: 9,
    profitMargin: 91,
  },
  {
    rank: 135,
    id: 'RISU',
    name: 'Cardguard',
    description:
      'Restriction of Thoracic Aorta, Ascending/Arch with Extraluminal Device, Percutaneous Approach',
    url: 'https://smugmug.com',
    controlledStake: 70,
    profitMargin: 17,
  },
  {
    rank: 136,
    id: 'AMET',
    name: 'Alphazap',
    description:
      'Occlusion of Right Foot Vein, Percutaneous Endoscopic Approach',
    url: 'https://360.cn',
    controlledStake: 35,
    profitMargin: 46,
  },
  {
    rank: 137,
    id: 'LACU',
    name: 'Zontrax',
    description:
      'Bypass Left Atrium to Left Pulmonary Vein with Autologous Arterial Tissue, Percutaneous Endoscopic Approach',
    url: 'https://hostgator.com',
    controlledStake: 27,
    profitMargin: 5,
  },
  {
    rank: 138,
    id: 'EUXX',
    name: 'Stronghold',
    description:
      'Excision of Right Hand Vein, Percutaneous Endoscopic Approach, Diagnostic',
    url: 'https://cyberchimps.com',
    controlledStake: 30,
    profitMargin: 95,
  },
  {
    rank: 139,
    id: 'NULL',
    name: 'Regrant',
    description:
      'Revision of Nonautologous Tissue Substitute in Prostate and Seminal Vesicles, External Approach',
    url: 'http://patch.com',
    controlledStake: 98,
    profitMargin: 76,
    retiring: '2019-07-17T20:58:07Z',
  },
  {
    rank: 140,
    id: 'RHON',
    name: 'Fintone',
    description: 'Bypass Transverse Colon to Transverse Colon, Open Approach',
    url: 'http://amazon.co.jp',
    controlledStake: 1,
    profitMargin: 99,
  },
  {
    rank: 141,
    id: 'EUXX',
    name: 'Hatity',
    description:
      'Drainage of Lumbar Nerve with Drainage Device, Percutaneous Approach',
    url: 'http://cbslocal.com',
    controlledStake: 68,
    profitMargin: 69,
  },
  {
    rank: 142,
    id: 'VELI',
    name: 'Latlux',
    description: 'Individual Psychotherapy, Behavioral',
    url: 'http://alexa.com',
    controlledStake: 93,
    profitMargin: 76,
  },
  {
    rank: 143,
    id: 'INTE',
    name: 'Mat Lam Tam',
    description:
      'Bypass Left Internal Iliac Artery to Right Femoral Artery with Synthetic Substitute, Open Approach',
    url: 'http://purevolume.com',
    controlledStake: 26,
    profitMargin: 87,
  },
  {
    rank: 144,
    id: 'INTE',
    name: 'Fintone',
    description:
      'Fusion of 8 or more Thoracic Vertebral Joints with Synthetic Substitute, Posterior Approach, Posterior Column, Percutaneous Approach',
    url: 'http://tmall.com',
    controlledStake: 77,
    profitMargin: 77,
    retiring: '2019-09-30T06:11:12Z',
  },
  {
    rank: 145,
    id: 'CRAS',
    name: 'Hatity',
    description:
      'Dilation of Face Artery, Bifurcation, with Three Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach',
    url: 'http://cargocollective.com',
    controlledStake: 20,
    profitMargin: 69,
  },
  {
    rank: 146,
    id: 'ULLA',
    name: 'Asoka',
    description:
      'Excision of Cerebellum, Percutaneous Endoscopic Approach, Diagnostic',
    url: 'https://ovh.net',
    controlledStake: 53,
    profitMargin: 38,
  },
  {
    rank: 147,
    id: 'RUTR',
    name: 'Transcof',
    description:
      'Release Right Internal Iliac Artery, Percutaneous Endoscopic Approach',
    url: 'https://reddit.com',
    controlledStake: 31,
    profitMargin: 13,
  },
  {
    rank: 148,
    id: 'ETXX',
    name: 'Alpha',
    description:
      'Revision of Autologous Tissue Substitute in Left Toe Phalanx, Percutaneous Endoscopic Approach',
    url: 'http://flickr.com',
    controlledStake: 30,
    profitMargin: 61,
    retiring: '2019-12-11T10:00:52Z',
  },
  {
    rank: 149,
    id: 'NULL',
    name: 'Daltfresh',
    description:
      'Revision of Extraluminal Device in Epididymis and Spermatic Cord, Percutaneous Approach',
    url: 'https://issuu.com',
    controlledStake: 5,
    profitMargin: 75,
  },
  {
    rank: 150,
    id: 'SOCI',
    name: 'Zoolab',
    description:
      'Dilation of Right Kidney Pelvis with Intraluminal Device, Via Natural or Artificial Opening',
    url: 'http://youtu.be',
    controlledStake: 42,
    profitMargin: 86,
  },
  {
    rank: 151,
    id: 'TINC',
    name: 'Cardguard',
    description:
      'Removal of Infusion Device from Left Ankle Joint, Open Approach',
    url: 'https://cbc.ca',
    controlledStake: 99,
    profitMargin: 79,
  },
  {
    rank: 152,
    id: 'ATXX',
    name: 'Redhold',
    description:
      'Plain Radiography of Right Internal Mammary Bypass Graft using Low Osmolar Contrast',
    url: 'https://utexas.edu',
    controlledStake: 95,
    profitMargin: 37,
    retiring: '2019-12-17T16:25:04Z',
  },
  {
    rank: 153,
    id: 'NUNC',
    name: 'Zathin',
    description:
      'Replacement of Left Internal Iliac Artery with Autologous Tissue Substitute, Open Approach',
    url: 'https://ow.ly',
    controlledStake: 92,
    profitMargin: 69,
  },
  {
    rank: 154,
    id: 'ERAT',
    name: 'Cardguard',
    description:
      'Bypass Left Pulmonary Artery from Carotid with Zooplastic Tissue, Open Approach',
    url: 'https://icq.com',
    controlledStake: 33,
    profitMargin: 75,
    retiring: '2019-06-07T05:42:22Z',
  },
  {
    rank: 155,
    id: 'BLAN',
    name: 'Treeflex',
    description: 'Dilation of Thoracic Aorta, Descending, Open Approach',
    url: 'http://vinaora.com',
    controlledStake: 70,
    profitMargin: 45,
  },
  {
    rank: 156,
    id: 'CURA',
    name: 'Cookley',
    description:
      'Bypass Left Subclavian Artery to Bilateral Lower Leg Artery with Synthetic Substitute, Open Approach',
    url: 'http://g.co',
    controlledStake: 40,
    profitMargin: 55,
  },
  {
    rank: 157,
    id: 'VENE',
    name: 'Cardify',
    description:
      'Revision of Synthetic Substitute in Left Humeral Shaft, Percutaneous Approach',
    url: 'http://xrea.com',
    controlledStake: 6,
    profitMargin: 12,
  },
  {
    rank: 158,
    id: 'RISU',
    name: 'Greenlam',
    description: 'Release Left Abdomen Bursa and Ligament, Open Approach',
    url: 'https://nsw.gov.au',
    controlledStake: 90,
    profitMargin: 99,
  },
  {
    rank: 159,
    id: 'LUCT',
    name: 'Transcof',
    description: 'Immobilization of Left Toe using Brace',
    url: 'https://gravatar.com',
    controlledStake: 75,
    profitMargin: 26,
  },
  {
    rank: 160,
    id: 'CONG',
    name: 'Domainer',
    description: 'Drainage of Skull, Percutaneous Approach',
    url: 'http://soup.io',
    controlledStake: 14,
    profitMargin: 19,
  },
  {
    rank: 161,
    id: 'LIGU',
    name: 'Treeflex',
    description:
      'Destruction of Right Internal Mammary Lymphatic, Open Approach',
    url: 'https://example.com',
    controlledStake: 84,
    profitMargin: 26,
  },
  {
    rank: 162,
    id: 'TINC',
    name: 'Keylex',
    description: 'Drainage of Brain, Open Approach',
    url: 'https://yandex.ru',
    controlledStake: 69,
    profitMargin: 22,
    retiring: '2019-09-15T15:16:26Z',
  },
  {
    rank: 163,
    id: 'SITX',
    name: 'Subin',
    description: 'Excision of Left Upper Lung Lobe, Open Approach, Diagnostic',
    url: 'https://list-manage.com',
    controlledStake: 72,
    profitMargin: 73,
  },
  {
    rank: 164,
    id: 'AMET',
    name: 'Sonsing',
    description:
      'Dilation of Right External Carotid Artery with Two Drug-eluting Intraluminal Devices, Percutaneous Approach',
    url: 'https://com.com',
    controlledStake: 59,
    profitMargin: 98,
  },
  {
    rank: 165,
    id: 'LOBO',
    name: 'Tresom',
    description:
      'Replacement of Nasal Turbinate with Synthetic Substitute, Percutaneous Approach',
    url: 'http://vimeo.com',
    controlledStake: 62,
    profitMargin: 81,
  },
  {
    rank: 166,
    id: 'JUST',
    name: 'Quo Lux',
    description: 'Drainage of Coccyx, Percutaneous Endoscopic Approach',
    url: 'https://whitehouse.gov',
    controlledStake: 79,
    profitMargin: 67,
  },
  {
    rank: 167,
    id: 'MUSX',
    name: 'Trippledex',
    description: 'Reattachment of Right Buttock, Open Approach',
    url: 'https://webs.com',
    controlledStake: 34,
    profitMargin: 37,
  },
  {
    rank: 168,
    id: 'POTE',
    name: 'Fixflex',
    description:
      'Physical Rehabilitation and Diagnostic Audiology, Rehabilitation, Device Fitting',
    url: 'http://blogs.com',
    controlledStake: 85,
    profitMargin: 98,
  },
  {
    rank: 169,
    id: 'MATT',
    name: 'Fintone',
    description:
      'Supplement Left Pulmonary Vein with Synthetic Substitute, Percutaneous Endoscopic Approach',
    url: 'http://amazon.co.jp',
    controlledStake: 59,
    profitMargin: 84,
  },
  {
    rank: 170,
    id: 'MASS',
    name: 'Overhold',
    description:
      'Removal of Autologous Tissue Substitute from Vas Deferens, Via Natural or Artificial Opening Endoscopic',
    url: 'http://ask.com',
    controlledStake: 15,
    profitMargin: 87,
    retiring: '2019-06-19T21:07:45Z',
  },
  {
    rank: 171,
    id: 'PURU',
    name: 'Cardguard',
    description:
      'Removal of Infusion Device from Uterus and Cervix, Via Natural or Artificial Opening Endoscopic',
    url: 'https://ucla.edu',
    controlledStake: 63,
    profitMargin: 23,
    retiring: '2019-09-24T19:07:59Z',
  },
  {
    rank: 172,
    id: 'NASC',
    name: 'Bigtax',
    description: 'Motor Speech Treatment using Voice Analysis Equipment',
    url: 'http://aol.com',
    controlledStake: 47,
    profitMargin: 42,
  },
  {
    rank: 173,
    id: 'INXX',
    name: 'Temp',
    description:
      'Occlusion of Right Vertebral Artery with Extraluminal Device, Percutaneous Approach',
    url: 'https://discovery.com',
    controlledStake: 21,
    profitMargin: 53,
  },
  {
    rank: 174,
    id: 'EROS',
    name: 'Sonair',
    description:
      'Extirpation of Matter from Right Eustachian Tube, Percutaneous Endoscopic Approach',
    url: 'http://paypal.com',
    controlledStake: 27,
    profitMargin: 11,
  },
  {
    rank: 175,
    id: 'PROI',
    name: 'Bitwolf',
    description:
      'Drainage of Head and Neck Tendon, Percutaneous Approach, Diagnostic',
    url: 'http://issuu.com',
    controlledStake: 29,
    profitMargin: 42,
    retiring: '2019-11-27T14:38:44Z',
  },
  {
    rank: 176,
    id: 'VELI',
    name: 'Kanlam',
    description:
      'High Dose Rate (HDR) Brachytherapy of Pituitary Gland using Iodine 125 (I-125)',
    url: 'http://ucla.edu',
    controlledStake: 45,
    profitMargin: 26,
    retiring: '2019-12-13T20:36:58Z',
  },
  {
    rank: 177,
    id: 'UTXX',
    name: 'Konklab',
    description:
      'Removal of Internal Fixation Device from Right Radius, Percutaneous Endoscopic Approach',
    url: 'https://princeton.edu',
    controlledStake: 72,
    profitMargin: 85,
  },
  {
    rank: 178,
    id: 'VEST',
    name: 'Transcof',
    description:
      'Revision of Monitoring Device in Ureter, Via Natural or Artificial Opening',
    url: 'https://sfgate.com',
    controlledStake: 55,
    profitMargin: 59,
    retiring: '2019-05-30T03:32:14Z',
  },
  {
    rank: 179,
    id: 'ACCU',
    name: 'Kanlam',
    description:
      'Insertion of Infusion Device into Mediastinum, Percutaneous Approach',
    url: 'https://usa.gov',
    controlledStake: 55,
    profitMargin: 21,
  },
  {
    rank: 180,
    id: 'MIXX',
    name: 'Fix San',
    description:
      'Computerized Tomography (CT Scan) of Bilateral Kidneys using Other Contrast',
    url: 'http://ca.gov',
    controlledStake: 64,
    profitMargin: 45,
  },
  {
    rank: 181,
    id: 'ESTX',
    name: 'Viva',
    description: 'Repair Right Palatine Bone, Open Approach',
    url: 'http://trellian.com',
    controlledStake: 49,
    profitMargin: 44,
    retiring: '2019-06-26T06:57:15Z',
  },
  {
    rank: 182,
    id: 'ELEM',
    name: 'Span',
    description:
      'Revision of Infusion Device in Spinal Cord, External Approach',
    url: 'http://phoca.cz',
    controlledStake: 72,
    profitMargin: 43,
  },
  {
    rank: 183,
    id: 'SAPI',
    name: 'Lotstring',
    description:
      'Bypass Left Hand Vein to Upper Vein with Autologous Venous Tissue, Percutaneous Endoscopic Approach',
    url: 'http://pen.io',
    controlledStake: 55,
    profitMargin: 3,
  },
  {
    rank: 184,
    id: 'FEUG',
    name: 'Ventosanzap',
    description:
      'Range of Motion and Joint Mobility Treatment of Musculoskeletal System - Head and Neck',
    url: 'http://shutterfly.com',
    controlledStake: 71,
    profitMargin: 63,
    retiring: '2019-05-31T21:44:37Z',
  },
  {
    rank: 185,
    id: 'PORT',
    name: 'Otcom',
    description:
      'Revision of Drainage Device in Left Toe Phalangeal Joint, Percutaneous Endoscopic Approach',
    url: 'http://example.com',
    controlledStake: 9,
    profitMargin: 11,
  },
  {
    rank: 186,
    id: 'UTXX',
    name: 'Holdlamis',
    description: 'Extraction of Back Skin, External Approach',
    url: 'http://narod.ru',
    controlledStake: 5,
    profitMargin: 34,
  },
  {
    rank: 187,
    id: 'MASS',
    name: 'Konklux',
    description:
      'Replacement of Left Lower Eyelid with Autologous Tissue Substitute, External Approach',
    url: 'https://who.int',
    controlledStake: 50,
    profitMargin: 65,
  },
  {
    rank: 188,
    id: 'LOBO',
    name: 'Opela',
    description:
      'Supplement Thoracolumbar Vertebral Joint with Nonautologous Tissue Substitute, Open Approach',
    url: 'https://fda.gov',
    controlledStake: 74,
    profitMargin: 52,
  },
  {
    rank: 189,
    id: 'UTXX',
    name: 'Hatity',
    description:
      'Bypass Thoracic Aorta, Descending to Subclavian, Open Approach',
    url: 'http://cisco.com',
    controlledStake: 35,
    profitMargin: 71,
  },
  {
    rank: 190,
    id: 'EROS',
    name: 'Tin',
    description:
      'Insertion of Infusion Device into Left Ankle Joint, Percutaneous Endoscopic Approach',
    url: 'http://reuters.com',
    controlledStake: 50,
    profitMargin: 37,
    retiring: '2019-11-05T17:03:28Z',
  },
  {
    rank: 191,
    id: 'DONE',
    name: 'Cardify',
    description:
      'Bypass Right External Iliac Artery to Bilateral Internal Iliac Arteries with Autologous Arterial Tissue, Percutaneous Endoscopic Approach',
    url: 'http://tinyurl.com',
    controlledStake: 14,
    profitMargin: 75,
    retiring: '2019-11-20T00:07:37Z',
  },
  {
    rank: 192,
    id: 'DIAM',
    name: 'Rank',
    description:
      'Revision of Internal Fixation Device in Right Knee Joint, Open Approach',
    url: 'http://cnn.com',
    controlledStake: 88,
    profitMargin: 69,
  },
  {
    rank: 193,
    id: 'IDXX',
    name: 'Daltfresh',
    description:
      'Introduction of Destructive Agent into Nose, Percutaneous Approach',
    url: 'http://washington.edu',
    controlledStake: 9,
    profitMargin: 94,
    retiring: '2019-07-14T14:37:52Z',
  },
  {
    rank: 194,
    id: 'ULTR',
    name: 'Toughjoyfax',
    description: 'Drainage of Left Upper Arm Tendon, Open Approach, Diagnostic',
    url: 'http://twitpic.com',
    controlledStake: 78,
    profitMargin: 60,
  },
  {
    rank: 195,
    id: 'FAUC',
    name: 'Konklux',
    description:
      'Occlusion of Right Internal Mammary Lymphatic with Intraluminal Device, Open Approach',
    url: 'http://yahoo.com',
    controlledStake: 47,
    profitMargin: 81,
  },
  {
    rank: 196,
    id: 'AUGU',
    name: 'Fixflex',
    description:
      'Introduction of Analgesics, Hypnotics, Sedatives into Female Reproductive, Percutaneous Approach',
    url: 'https://un.org',
    controlledStake: 87,
    profitMargin: 59,
  },
  {
    rank: 197,
    id: 'DAPI',
    name: 'Zoolab',
    description:
      'Occlusion of Gastric Artery, Percutaneous Endoscopic Approach',
    url: 'https://msn.com',
    controlledStake: 95,
    profitMargin: 41,
  },
  {
    rank: 198,
    id: 'PLAT',
    name: 'Tampflex',
    description:
      'Introduction of Other Antineoplastic into Female Reproductive, Via Natural or Artificial Opening Endoscopic',
    url: 'http://gmpg.org',
    controlledStake: 13,
    profitMargin: 94,
  },
  {
    rank: 199,
    id: 'SEDX',
    name: 'Subin',
    description:
      'Replacement of Right Hip Joint, Acetabular Surface with Polyethylene Synthetic Substitute, Cemented, Open Approach',
    url: 'https://un.org',
    controlledStake: 43,
    profitMargin: 11,
    retiring: '2019-06-28T10:24:57Z',
  },
  {
    rank: 200,
    id: 'AXX',
    name: 'Job',
    description: 'Change Bandage on Left Lower Extremity',
    url: 'http://fotki.com',
    controlledStake: 54,
    profitMargin: 48,
  },
];
