export const actions: string;
export const columnDirection: string;
export const content: string;
export const contentWithActions: string;
export const contentWrapper: string;
export const dialogWrapper: string;
export const rowDirection: string;
export const subtitle: string;
export const title: string;
