export const addressElement: string;
export const addressId: string;
export const addressIdBegin: string;
export const addressIdEnd: string;
export const component: string;
export const ellipsis: string;
export const ellipsisIsVisible: string;
export const invalidAddress: string;
export const usedWalletAddress: string;
