export const actionBtn: string;
export const component: string;
export const content: string;
export const date: string;
export const externalLink: string;
export const grey: string;
export const red: string;
export const themeDefault: string;
export const title: string;
