export const checkbox: string;
export const closeButton: string;
export const component: string;
export const description: string;
export const error: string;
export const errorMessage: string;
export const itnLink: string;
export const recoveryPhrase: string;
export const walletsDropdownWrapper: string;
