// @flow

// CardanoNode ipc channels
export const CARDANO_AWAIT_UPDATE_CHANNEL = 'CARDANO_AWAIT_UPDATE_CHANNEL';
export const CARDANO_STATE_CHANGE_CHANNEL = 'CARDANO_STATE_CHANGE_CHANNEL';
export const CARDANO_TLS_CONFIG_CHANNEL = 'CARDANO_TLS_CONFIG_CHANNEL';
export const CARDANO_RESTART_CHANNEL = 'CARDANO_RESTART_CHANNEL';
export const CARDANO_FAULT_INJECTION_CHANNEL = 'CARDANO_FAULT_INJECTION_CHANNEL';
export const CARDANO_STATUS_CHANNEL = 'CARDANO_STATUS_CHANNEL';

export const GO_TO_ADA_REDEMPTION_SCREEN_CHANNEL = 'GO_TO_ADA_REDEMPTION_SCREEN';
export const GO_TO_NETWORK_STATUS_SCREEN_CHANNEL = 'GO_TO_NETWORK_STATUS_SCREEN';
export const LOAD_ASSET_CHANNEL = 'LOAD_ASSET';
export const OPEN_ABOUT_DIALOG_CHANNEL = 'OPEN_ABOUT_DIALOG';
export const OPEN_EXTERNAL_URL_CHANNEL = 'OPEN_EXTERNAL_URL';
