// @flow

export const DIALOGS = {
  ABOUT: 'ABOUT_DIALOG',
  NETWORK_STATUS: 'NETWORK_STATUS_DIALOG',
};

export const SCREENS = {
  ADA_REDEMPTION: 'ADA_REDEMPTION_SCREEN',
  BLOCK_CONSOLIDATION: 'BLOCK_CONSOLIDATION_SCREEN',
};

export const ERRORS = {
  INVALID_REDEMPTION_CERTIFICATE_ERROR: 'INVALID_REDEMPTION_CERTIFICATE_ERROR',
};
