// @flow
export const DIALOGS = {
  ABOUT: 'ABOUT_DIALOG',
  BLOCK_CONSOLIDATION: 'BLOCK_CONSOLIDATION_DIALOG',
  DAEDALUS_DIAGNOSTICS: 'DAEDALUS_DIAGNOSTICS_DIALOG',
  INTERNET_CONNECTION_STATUS: 'INTERNET_CONNECTION_STATUS_DIALOG',
};

export const NOTIFICATIONS = {
  DOWNLOAD_LOGS: 'DOWNLOAD_LOGS_NOTIFICATION',
};
