// @flow
export const DIALOGS = {
  ABOUT: 'ABOUT_DIALOG',
  BLOCK_CONSOLIDATION: 'BLOCK_CONSOLIDATION_DIALOG',
  DAEDALUS_DIAGNOSTICS: 'DAEDALUS_DIAGNOSTICS_DIALOG',
};

export const SCREENS = {
  ADA_REDEMPTION: 'ADA_REDEMPTION_SCREEN',
};

export const ERRORS = {
  INVALID_REDEMPTION_CERTIFICATE_ERROR: 'INVALID_REDEMPTION_CERTIFICATE_ERROR',
};

export const NOTIFICATIONS = {
  DOWNLOAD_LOGS: 'DOWNLOAD_LOGS_NOTIFICATION',
};
