export const content: string;
export const header: string;
export const headerError: string;
export const headerLeftSlot: string;
export const headerRightSlot: string;
export const headerSlot: string;
export const inputList: string;
export const inputWrapper: string;
export const root: string;
