#!/usr/bin/env bash
#
# See /var/log/install.log to debug this

src_pkg="$1"
dst_root="$2"
dst_mount="$3"
sys_root="$4"

./dockutil --add "${dst_root}/Daedalus.app" --allhomes

set -x
ls ${dst_root}
ls -l ${dst_root}/Daedalus.app
ls -l ${dst_root}/Daedalus.app/Contents
ls -l ${dst_root}/Daedalus.app/Contents/MacOS
cd "${dst_root}/Daedalus.app/Contents/MacOS/"

bash ./build-certificates-unix.sh
